import type { Product } from "./types";

export const products: Product[] = [
  // SMARTPHONES
  {
    id: "phone-redmi-a",
    sectionId: "smartphones",
    bandId: "budget",
    brand: "Xiaomi",
    name: "Redmi A-серія",
    tags: ["для мами", "перший телефон", "до 10к"],
    forWhom: "Батьки, підліток, запасний телефон",
    pros: ["Простий і зрозумілий", "Достатньо для дзвінків і месенджерів", "Недорогий вхід у Android"],
    con: "Не для важких ігор і топової камери",
    upsell: ["Чохол", "Скло", "Кабель / блок"],
    pitch: "Якщо треба просто надійний телефон без переплат — ось комфортний бюджетний варіант.",
    specs: {
      display: "6.5–6.7\" HD+",
      memory: "64–128 ГБ / 3–4 ГБ",
      camera: "Базова",
      battery: "5000 мА·г",
      chip: "Базовий, для щодня",
    },
    isHit: true,
    relatedIds: ["phone-samsung-a", "phone-moto-g"],
  },
  {
    id: "phone-samsung-a",
    sectionId: "smartphones",
    bandId: "budget",
    brand: "Samsung",
    name: "Galaxy A0x / A1x",
    tags: ["samsung", "для мами", "до 12к"],
    forWhom: "Хто хоче звичний Samsung за невеликі гроші",
    pros: ["Зрозумілий One UI", "Добра підтримка оновлень у лінійці", "Легко пояснити батькам"],
    con: "За ті ж гроші конкуренти можуть дати більше пам’яті",
    upsell: ["Чохол Samsung", "Скло", "Powerbank"],
    pitch: "Якщо людина вже «на Samsung» — залишаємось у знайомій системі без стрибка в ціну.",
    specs: {
      display: "6.5\"+",
      memory: "64–128 ГБ",
      camera: "Базова / середня",
      battery: "~5000 мА·г",
      chip: "Плавний щодень",
    },
    isHit: true,
    relatedIds: ["phone-redmi-a", "phone-samsung-a3"],
  },
  {
    id: "phone-moto-g",
    sectionId: "smartphones",
    bandId: "budget",
    brand: "Motorola",
    name: "Moto G / E",
    tags: ["чистий android", "бюджет"],
    forWhom: "Хто хоче простий Android без зайвого ПО",
    pros: ["Чистіший інтерфейс", "Часто хороший звук динаміка", "Зручні жести"],
    con: "Менше аксесуарів «під бренд» на місці",
    upsell: ["Універсальний чохол", "Скло"],
    pitch: "Бюджетний телефон «без зайвого шуму» в меню — зручно пояснювати новачкам.",
    specs: {
      display: "6.5\"+",
      memory: "64–128 ГБ",
      camera: "Базова",
      battery: "5000 мА·г",
      chip: "Для щодня",
    },
    isHit: true,
    relatedIds: ["phone-redmi-a", "phone-samsung-a"],
  },
  {
    id: "phone-samsung-a3",
    sectionId: "smartphones",
    bandId: "mid",
    brand: "Samsung",
    name: "Galaxy A3x / A5x",
    tags: ["середній", "камера", "щодня"],
    forWhom: "Основний телефон на 2–3 роки",
    pros: ["Баланс камери й швидкості", "Нормальна автономність", "Впізнаваний бренд"],
    con: "За ті ж гроші Xiaomi інколи дає більше «залізом»",
    upsell: ["Чохол", "Скло", "Buds / навушники"],
    pitch: "Середній Samsung — універсальна відповідь «щоб і камера, і не гальмував».",
    specs: {
      display: "AMOLED 90–120 Гц",
      memory: "128–256 ГБ / 6–8 ГБ",
      camera: "Сильна для сегмента",
      battery: "5000 мА·г + швидка зарядка",
      chip: "Плавний UI",
    },
    isHit: true,
    relatedIds: ["phone-redmi-note", "phone-pixel-a"],
  },
  {
    id: "phone-redmi-note",
    sectionId: "smartphones",
    bandId: "mid",
    brand: "Xiaomi",
    name: "Redmi Note",
    tags: ["ціна/якість", "екран", "зарядка"],
    forWhom: "Хто хоче максимум характеристик за гроші",
    pros: ["Яскравий екран", "Швидка зарядка", "Багато пам’яті"],
    con: "Інтерфейс і реклама в ПО — треба попередити",
    upsell: ["Чохол", "Скло", "Кабель 67/120W якщо треба"],
    pitch: "Якщо клієнт рахує «що всередині за ціну» — Note майже завжди в топі розмови.",
    specs: {
      display: "AMOLED 120 Гц",
      memory: "128–256 ГБ / 8 ГБ",
      camera: "Універсальна",
      battery: "5000+ мА·г",
      chip: "Добре тягне ігри",
    },
    isHit: true,
    relatedIds: ["phone-samsung-a3", "phone-poco"],
  },
  {
    id: "phone-poco",
    sectionId: "smartphones",
    bandId: "mid",
    brand: "POCO",
    name: "POCO X / M",
    tags: ["ігри", "потужність"],
    forWhom: "Ігри й швидкість без переплати за бренд",
    pros: ["Потужний чип у сегменті", "Хороша автономність", "Ціна/продуктивність"],
    con: "Камера й ПЗ можуть бути простіші за Samsung",
    upsell: ["Кулер/чохол з вентиляцією", "Скло"],
    pitch: "Якщо кажуть «щоб тягнув ігри» — ведемо в POCO, а не в найдешевший A-серію.",
    specs: {
      display: "120 Гц",
      memory: "256 ГБ / 8 ГБ",
      camera: "Середня",
      battery: "5000+ мА·г",
      chip: "Ігровий акцент",
    },
    isHit: true,
    relatedIds: ["phone-redmi-note", "phone-samsung-a3"],
  },
  {
    id: "phone-pixel-a",
    sectionId: "smartphones",
    bandId: "mid",
    brand: "Google",
    name: "Pixel A-серія",
    tags: ["камера", "фото", "чистий android"],
    forWhom: "Фото й чистий Android",
    pros: ["Камера з розумним софтом", "Довгі оновлення", "Простота"],
    con: "Менше «вау» в залізі за ті ж гроші",
    upsell: ["Чохол", "Скло"],
    pitch: "Якщо пріоритет — щоб фото виходили «самі гарні», Pixel часто виграє розмову.",
    specs: {
      display: "OLED 90–120 Гц",
      memory: "128 ГБ",
      camera: "Топова обробка",
      battery: "Достатня на день",
      chip: "Плавний софт",
    },
    isHit: false,
    relatedIds: ["phone-samsung-a3", "phone-iphone-se"],
  },
  {
    id: "phone-iphone-se",
    sectionId: "smartphones",
    bandId: "premium",
    brand: "Apple",
    name: "iPhone (актуальні / SE)",
    tags: ["apple", "екосистема", "преміум"],
    forWhom: "Екосистема Apple, FaceTime, довга підтримка",
    pros: ["Стабільність iOS", "Тривалі оновлення", "Перепродаж"],
    con: "За ті ж гроші Android дає більше екрана/батареї",
    upsell: ["Чохол", "Швидке скло", "MagSafe / зарядка"],
    pitch: "Якщо вже AirPods/Mac або «хочу айфон» — не відговорюємо, допомагаємо обрати покоління під бюджет.",
    specs: {
      display: "OLED / LCD залежно від моделі",
      memory: "128–256 ГБ",
      camera: "Передбачувана якість",
      battery: "День при нормальному використанні",
      chip: "Дуже плавно",
    },
    isHit: true,
    relatedIds: ["phone-samsung-s", "phone-samsung-a3"],
  },
  {
    id: "phone-samsung-s",
    sectionId: "smartphones",
    bandId: "premium",
    brand: "Samsung",
    name: "Galaxy S / S FE",
    tags: ["флагман", "камера", "екран"],
    forWhom: "Максимум екрана, камери й швидкості на Android",
    pros: ["Контрастний AMOLED", "Гнучкі можливості", "S FE дешевший вхід у флагман"],
    con: "Ціна аксесуарів і обережність із комплектацією",
    upsell: ["Buds", "Чохол", "Скло"],
    pitch: "Преміум Android із «вау»-екраном — коли клієнт хоче топовий досвід без обов’язкового iPhone.",
    specs: {
      display: "Dynamic AMOLED 120 Гц",
      memory: "256 ГБ / 8–12 ГБ",
      camera: "Флагманська",
      battery: "Сильна + швидка зарядка",
      chip: "Топова плавність",
    },
    isHit: true,
    relatedIds: ["phone-iphone-se", "phone-redmi-note"],
  },

  // LAPTOPS
  {
    id: "laptop-office-budget",
    sectionId: "laptops",
    bandId: "budget",
    brand: "Lenovo / Acer / ASUS",
    name: "Офісний 15.6\" (бюджет)",
    tags: ["універ", "zoom", "excel", "до 20к"],
    forWhom: "Навчання, документи, браузер, Zoom",
    pros: ["Закриває базові задачі", "Звичний великий екран", "Легко пояснити батькам"],
    con: "Не для монтажу й важких ігор",
    upsell: ["Миша", "Сумка", "SSD більше якщо слот є"],
    pitch: "Для універу й офісу не треба ігровий ноут — беріть легкий офісний і вкладіть у SSD/мишу.",
    specs: {
      cpu: "Intel U / Ryzen U (базовий)",
      ram: "8 ГБ (краще 16)",
      ssd: "256–512 ГБ",
      display: "15.6\" Full HD",
      battery: "4–7 год офіс",
      weight: "~1.7–1.9 кг",
    },
    isHit: true,
    relatedIds: ["laptop-ultrabook-mid", "laptop-student-mid"],
  },
  {
    id: "laptop-student-mid",
    sectionId: "laptops",
    bandId: "mid",
    brand: "ASUS / Lenovo",
    name: "Універсал 16 ГБ",
    tags: ["робота", "16гб", "навчання"],
    forWhom: "Щоденна робота без гальм, багато вкладок",
    pros: ["16 ГБ ОЗП відчутно", "512 ГБ SSD комфортніше", "Тягне легший креатив"],
    con: "Ігри — лише легкі",
    upsell: ["Миша", "Підставка", "HDMI-хаб"],
    pitch: "Якщо людина працює з купою вкладок і Zoom — 16 ГБ це не «маркетинг», це спокій.",
    specs: {
      cpu: "Сучасний Intel/AMD",
      ram: "16 ГБ",
      ssd: "512 ГБ",
      display: "14–15.6\" IPS",
      battery: "6–9 год",
      weight: "1.4–1.8 кг",
    },
    isHit: true,
    relatedIds: ["laptop-office-budget", "laptop-creator-mid"],
  },
  {
    id: "laptop-ultrabook-mid",
    sectionId: "laptops",
    bandId: "mid",
    brand: "Lenovo / HP / Dell",
    name: "Тонкий робочий",
    tags: ["легкий", "в дорогу", "офіс"],
    forWhom: "Хто носить ноут щодня",
    pros: ["Менша вага", "Краща автономність", "Охайний вигляд"],
    con: "Слабше для ігор і апгрейду",
    upsell: ["Сумка-слінг", "USB-C хаб"],
    pitch: "Якщо ноут «живе» в рюкзаку — краще тонкий середній, ніж важкий бюджетний 15.6\".",
    specs: {
      cpu: "Енергоефективний",
      ram: "16 ГБ",
      ssd: "512 ГБ",
      display: "14\" IPS",
      battery: "8–12 год",
      weight: "~1.3–1.5 кг",
    },
    isHit: true,
    relatedIds: ["laptop-student-mid", "laptop-macbook"],
  },
  {
    id: "laptop-creator-mid",
    sectionId: "laptops",
    bandId: "mid",
    brand: "ASUS / Acer",
    name: "Під фото / легке відео",
    tags: ["фото", "відео", "колір"],
    forWhom: "Студенти креативу, фриланс",
    pros: ["Кращий екран", "Більше потужності", "Можна роститись у задачах"],
    con: "Шумніший і важчий за ультрабук",
    upsell: ["Миша", "Зовнішній SSD"],
    pitch: "Якщо є Lightroom/Premiere — одразу дивимось екран і ОЗП, а не «найдешевший великий».",
    specs: {
      cpu: "Потужніший U/H",
      ram: "16 ГБ",
      ssd: "512 ГБ–1 ТБ",
      display: "Full HD / 100% sRGB бажано",
      battery: "5–8 год",
      weight: "1.7–2.1 кг",
    },
    isHit: false,
    relatedIds: ["laptop-student-mid", "laptop-gaming"],
  },
  {
    id: "laptop-gaming",
    sectionId: "laptops",
    bandId: "premium",
    brand: "ASUS / Lenovo / MSI",
    name: "Ігровий з дискретною GPU",
    tags: ["ігри", "rtx", "преміум"],
    forWhom: "Ігри, 3D, важкий монтаж",
    pros: ["Дискретна відеокарта", "Висока частота екрана", "Запас потужності"],
    con: "Вага, шум, батарея в іграх слабка",
    upsell: ["Миша ігрова", "Підставка з охолодженням", "Гарнітура"],
    pitch: "Ігровий ноут беремо лише якщо є реальна задача. Інакше переплачують за шум і вагу.",
    specs: {
      cpu: "H-серія",
      ram: "16–32 ГБ",
      ssd: "512 ГБ–1 ТБ",
      display: "15.6–16\" 144 Гц+",
      battery: "Коротша в навантаженні",
      weight: "2.1–2.5 кг",
    },
    isHit: true,
    relatedIds: ["laptop-creator-mid", "laptop-macbook"],
  },
  {
    id: "laptop-macbook",
    sectionId: "laptops",
    bandId: "premium",
    brand: "Apple",
    name: "MacBook Air / Pro",
    tags: ["apple", "тихо", "батарея"],
    forWhom: "Екосистема Apple, тиша, автономність",
    pros: ["Дуже тихий", "Сильна батарея", "Якісний екран і збірка"],
    con: "Ціна апгрейд пам’яті, інша логіка портів",
    upsell: ["USB-C хаб", "Чохол / рукав"],
    pitch: "Якщо вже iPhone або важлива тиша й батарея — Air часто закриває розмову краще за Windows-ігровий.",
    specs: {
      cpu: "Apple Silicon",
      ram: "8–16 ГБ уніфікованої",
      ssd: "256–512 ГБ+",
      display: "Liquid Retina",
      battery: "Довга",
      weight: "~1.2–1.5 кг",
    },
    isHit: true,
    relatedIds: ["laptop-ultrabook-mid", "laptop-gaming"],
  },

  // TVS
  {
    id: "tv-43-budget",
    sectionId: "tvs",
    bandId: "budget",
    brand: "Hisense / Xiaomi / TCL",
    name: "43–50\" Full HD / базовий 4K",
    tags: ["кухня", "дача", "перший тв"],
    forWhom: "Кухня, кімната, невеликий бюджет",
    pros: ["Закриває YouTube і ТБ", "Невелика ціна", "Легко повісити"],
    con: "Картинка й звук простіші",
    upsell: ["Кріплення", "HDMI кабель", "Саундбар бюджет"],
    pitch: "На кухню не треба OLED — беріть адекватну діагональ і нормальний Smart.",
    specs: {
      size: "43–50\"",
      panel: "LCD / VA",
      hz: "60 Гц",
      smart: "WebOS / Vidaa / Google TV",
      hdmi: "2–3 HDMI",
    },
    isHit: true,
    relatedIds: ["tv-55-mid", "tv-50-mid"],
  },
  {
    id: "tv-50-mid",
    sectionId: "tvs",
    bandId: "mid",
    brand: "Samsung / Xiaomi / Hisense",
    name: "50–55\" 4K універсал",
    tags: ["вітальня", "4k", "netflix"],
    forWhom: "Основний ТВ у вітальні",
    pros: ["4K помітно на 50\"+", "Кращий Smart", "Баланс ціна/картинка"],
    con: "Звук усе ще варто підсилити саундбаром",
    upsell: ["Кріплення", "Саундбар", "HDMI 2.1 кабель"],
    pitch: "Для вітальні починаємо з 55\" якщо дозволяє відстань диван–ТВ.",
    specs: {
      size: "50–55\"",
      panel: "VA / IPS",
      hz: "60–120 Гц",
      smart: "Tizen / Google TV",
      hdmi: "3–4 HDMI",
    },
    isHit: true,
    relatedIds: ["tv-43-budget", "tv-55-qled"],
  },
  {
    id: "tv-55-mid",
    sectionId: "tvs",
    bandId: "mid",
    brand: "LG / Samsung",
    name: "55\" з кращим рухом",
    tags: ["спорт", "фільми"],
    forWhom: "Спорт, серіали, сімейний перегляд",
    pros: ["Приємніший рух", "Стабільний Smart", "Добре для щодня"],
    con: "До OLED/QLED ще крок по контрасту",
    upsell: ["Саундбар", "Кріплення"],
    pitch: "Якщо багато футболу й динамічного контенту — дивимось частоту/обробку руху, не лише діагональ.",
    specs: {
      size: "55\"",
      panel: "LCD високого рівня",
      hz: "120 Гц (або ефективна обробка)",
      smart: "webOS / Tizen",
      hdmi: "HDMI eARC",
    },
    isHit: true,
    relatedIds: ["tv-50-mid", "tv-55-oled"],
  },
  {
    id: "tv-55-qled",
    sectionId: "tvs",
    bandId: "premium",
    brand: "Samsung",
    name: "QLED 55–65\"",
    tags: ["яскравий", "день", "qled"],
    forWhom: "Світла вітальня, яскрава картинка",
    pros: ["Яскравість вдень", "Насичений колір", "Преміум-вигляд"],
    con: "Чорний не як у OLED",
    upsell: ["Саундбар mid/premium", "Кріплення"],
    pitch: "Світла кімната з вікнами — QLED часто практичніший за OLED.",
    specs: {
      size: "55–65\"",
      panel: "QLED",
      hz: "120 Гц",
      smart: "Tizen",
      hdmi: "HDMI 2.1",
    },
    isHit: true,
    relatedIds: ["tv-55-oled", "tv-55-mid"],
  },
  {
    id: "tv-55-oled",
    sectionId: "tvs",
    bandId: "premium",
    brand: "LG / Samsung",
    name: "OLED 55–65\"",
    tags: ["кино", "чорний", "oled"],
    forWhom: "Кіно ввечері, темна/напівтемна кімната",
    pros: ["Ідеальний чорний", "Контраст «вау»", "Ідеально для фільмів"],
    con: "Дорожче; в дуже світлій кімнаті менше переваг",
    upsell: ["Якісний саундбар", "Кріплення"],
    pitch: "Якщо дивляться фільми ввечері й хочуть «як у кіно» — OLED пояснюється за 20 секунд.",
    specs: {
      size: "55–65\"",
      panel: "OLED",
      hz: "120 Гц",
      smart: "webOS / Tizen",
      hdmi: "HDMI 2.1",
    },
    isHit: true,
    relatedIds: ["tv-55-qled", "tv-55-mid"],
  },

  // FRIDGES
  {
    id: "fridge-small",
    sectionId: "fridges",
    bandId: "budget",
    brand: "Nord / Saturn / Beko",
    name: "Компакт / двокамерний малий",
    tags: ["оренда", "1-2 особи"],
    forWhom: "1–2 особи, орендована квартира",
    pros: ["Недорогий вхід", "Менше місця", "Закриває базові потреби"],
    con: "Малий об’єм і простіші функції",
    upsell: ["Стабілізатор / мережевий фільтр", "Органайзери"],
    pitch: "На оренду не беремо «сімейний шкаф» — спочатку виміри й об’єм під реальну їжу.",
    specs: {
      volume: "120–250 л",
      frost: "Крапельна / простий No Frost",
      energy: "A+ / A++ орієнтир",
      zones: "Базові",
      noise: "Середній",
    },
    isHit: true,
    relatedIds: ["fridge-family-nf", "fridge-narrow"],
  },
  {
    id: "fridge-narrow",
    sectionId: "fridges",
    bandId: "budget",
    brand: "Beko / Indesit",
    name: "Вузький під нішу",
    tags: ["вузький", "виміри"],
    forWhom: "Маленька кухня з вузькою нішею",
    pros: ["Влазить у складні кухні", "Нормальний об’єм при малій ширині", "Практичний вибір"],
    con: "Менше «преміум»-функцій",
    upsell: ["Вимірювальна консультація", "Фільтр"],
    pitch: "Спочатку сантиметри ніші, потім бренд. Вузький правильний кращий за широкий «майже влазить».",
    specs: {
      volume: "200–280 л",
      frost: "No Frost бажано",
      energy: "Економний клас",
      zones: "2 камери",
      noise: "Середній",
    },
    isHit: true,
    relatedIds: ["fridge-small", "fridge-family-nf"],
  },
  {
    id: "fridge-family-nf",
    sectionId: "fridges",
    bandId: "mid",
    brand: "Samsung / LG / Beko",
    name: "Сімейний No Frost",
    tags: ["сімʼя", "no frost", "середній"],
    forWhom: "Сім’я 3–4 особи",
    pros: ["Не треба розморожувати вручну", "Більший об’єм", "Зручні полиці"],
    con: "Дорожчий і може бути гучнішим за преміум",
    upsell: ["Фільтр / стабілізація", "Гарантійний пакет"],
    pitch: "No Frost для сім’ї — це не фішка, а щоб раз на рік не влаштовувати льодовиковий період.",
    specs: {
      volume: "300–400 л",
      frost: "No Frost",
      energy: "Вищий клас",
      zones: "Зона свіжості інколи",
      noise: "Середній / тихіший",
    },
    isHit: true,
    relatedIds: ["fridge-premium", "fridge-small"],
  },
  {
    id: "fridge-premium",
    sectionId: "fridges",
    bandId: "premium",
    brand: "Samsung / LG / Bosch",
    name: "Великий з зонами / інвертор",
    tags: ["тихий", "зони", "преміум"],
    forWhom: "Велика сім’я, хочуть тишу й організацію",
    pros: ["Більше зон зберігання", "Тихіший інвертор", "Зручність на роки"],
    con: "Ціна й розмір треба точно виміряти",
    upsell: ["Встановлення / виносу старого"],
    pitch: "Преміум холодильник продаємо зручністю життя, не «більше літер на наліпці».",
    specs: {
      volume: "400 л+",
      frost: "No Frost",
      energy: "Високий",
      zones: "Свіжість / м’ясо / freeze",
      noise: "Низький",
    },
    isHit: true,
    relatedIds: ["fridge-family-nf", "fridge-narrow"],
  },

  // WASHERS
  {
    id: "washer-5-6",
    sectionId: "washers",
    bandId: "budget",
    brand: "Indesit / Beko / Saturn",
    name: "5–6 кг базова",
    tags: ["1-2 особи", "бюджет"],
    forWhom: "1–2 особи, невеликі партії білизни",
    pros: ["Недорога", "Компактніша", "Базові програми є"],
    con: "Для сім’ї з дітьми буде тісно",
    upsell: ["Засіб / сітки", "Шланги / фільтр"],
    pitch: "Якщо стирають раз на тиждень і живуть удвох — 6 кг часто достатньо.",
    specs: {
      load: "5–6 кг",
      type: "Фронтальна",
      rpm: "1000–1200",
      inverter: "Часто ні",
      programs: "Базові + швидка",
    },
    isHit: true,
    relatedIds: ["washer-7-inv", "washer-8-9"],
  },
  {
    id: "washer-7-inv",
    sectionId: "washers",
    bandId: "mid",
    brand: "LG / Samsung / Beko",
    name: "7–8 кг з інвертором",
    tags: ["сімʼя", "інвертор", "тихіше"],
    forWhom: "Сім’я 3 особи, регулярні прання",
    pros: ["Інвертор = тихіше й довше служить", "Нормальний об’єм барабана", "Кращі програми"],
    con: "Дорожче за «просту» 6 кг",
    upsell: ["Засіб", "Гарантія", "Підключення"],
    pitch: "Інвертор пояснюємо просто: менше шуму, менше вібрацій, двигун живе спокійніше.",
    specs: {
      load: "7–8 кг",
      type: "Фронтальна",
      rpm: "1200–1400",
      inverter: "Так",
      programs: "Бавовна, еко, швидка, дитячі",
    },
    isHit: true,
    relatedIds: ["washer-5-6", "washer-8-9"],
  },
  {
    id: "washer-8-9",
    sectionId: "washers",
    bandId: "premium",
    brand: "LG / Samsung / Bosch",
    name: "8–10 кг пар / тиша",
    tags: ["велике завантаження", "пар", "преміум"],
    forWhom: "Велика сім’я, алергія, хочуть преміум-догляд",
    pros: ["Великі партії білизни", "Пар / гігієна", "Тихіше й розумніші режими"],
    con: "Ціна й потреба в місці",
    upsell: ["Сушильна в пару", "Підключення"],
    pitch: "Якщо часто перуть постіль і рушники — завантаження й пар важливіші за «ще одну програмку».",
    specs: {
      load: "8–10 кг",
      type: "Фронтальна",
      rpm: "1400",
      inverter: "Так",
      programs: "Пар, алергія, тихі нічні",
    },
    isHit: true,
    relatedIds: ["washer-7-inv", "washer-5-6"],
  },

  // ACS
  {
    id: "ac-09",
    sectionId: "acs",
    bandId: "budget",
    brand: "Cooper&Hunter / Osaka / Olmo",
    name: "09 на кімнату ~20 м²",
    tags: ["20м2", "спальня"],
    forWhom: "Спальня / невелика кімната",
    pros: ["Правильний підбір під площу", "Доступний вхід", "Закриває літо"],
    con: "На велику залу буде слабко",
    upsell: ["Монтаж", "Кронштейни", "Чистка раз на сезон"],
    pitch: "Кондиціонер підбираємо по площі, не по «найдешевшому великому».",
    specs: {
      area: "~20 м² / 09",
      inverter: "Інколи on/off",
      energy: "Середній",
      noise: "Прийнятний",
      wifi: "Рідко",
    },
    isHit: true,
    relatedIds: ["ac-12-inv", "ac-18"],
  },
  {
    id: "ac-12-inv",
    sectionId: "acs",
    bandId: "mid",
    brand: "Samsung / LG / C&H",
    name: "12 інвертор ~25–35 м²",
    tags: ["інвертор", "дім", "тихіше"],
    forWhom: "Основна кімната в квартирі",
    pros: ["Інвертор тримає температуру рівніше", "Економніше", "Тихіше"],
    con: "Дорожчий за on/off",
    upsell: ["Монтаж під ключ", "Wi‑Fi модуль якщо є"],
    pitch: "Інвертор — це не маркетинг: менше циклів увімк/вимк і комфортніший сон.",
    specs: {
      area: "25–35 м² / 12",
      inverter: "Так",
      energy: "Вищий клас",
      noise: "Низький на мінімумі",
      wifi: "Часто опція",
    },
    isHit: true,
    relatedIds: ["ac-09", "ac-18"],
  },
  {
    id: "ac-18",
    sectionId: "acs",
    bandId: "premium",
    brand: "Daikin / Mitsubishi / LG",
    name: "18+ / преміум інвертор",
    tags: ["велика кімната", "тихо", "преміум"],
    forWhom: "Велика кімната / вимогливі до шуму",
    pros: ["Запас потужності", "Тиша", "Надійність сегмента"],
    con: "Ціна техніки + монтаж",
    upsell: ["Якісний монтаж", "Сервіс"],
    pitch: "На велику залу й преміум-очікування краще одразу правильний BTU, ніж «потужний бюджет» із шумом.",
    specs: {
      area: "35–50 м² / 18+",
      inverter: "Так",
      energy: "Високий",
      noise: "Дуже низький у топів",
      wifi: "Часто є",
    },
    isHit: true,
    relatedIds: ["ac-12-inv", "ac-09"],
  },

  // MICROWAVES
  {
    id: "mw-basic",
    sectionId: "microwaves",
    bandId: "budget",
    brand: "Saturn / Liberton / Gorenje",
    name: "20 л соло",
    tags: ["підігрів", "розморозка"],
    forWhom: "Підігрів їжі й розморозка",
    pros: ["Недорого", "Займає мало місця", "Робить 90% задач"],
    con: "Без гриля/конвекції",
    upsell: ["Тарілки для НВЧ", "Кришка"],
    pitch: "Якщо тільки гріти — не продаємо конвекцію «про всяк випадок».",
    specs: {
      volume: "20 л",
      power: "700–800 Вт",
      mode: "Соло",
      controls: "Механіка / прості кнопки",
    },
    isHit: true,
    relatedIds: ["mw-grill", "mw-convection"],
  },
  {
    id: "mw-grill",
    sectionId: "microwaves",
    bandId: "mid",
    brand: "Samsung / LG / Whirlpool",
    name: "23–25 л з грилем",
    tags: ["гриль", "сімʼя"],
    forWhom: "Сім’я, інколи запікають/підрум’янюють",
    pros: ["Більший об’єм", "Гриль додає сценарії", "Зручніші програми"],
    con: "Дорожче й трохи більше місця",
    upsell: ["Посуд для гриля"],
    pitch: "Гриль має сенс, якщо реально будуть курочка/тости, а не лише суп.",
    specs: {
      volume: "23–25 л",
      power: "800–900 Вт",
      mode: "Гриль",
      controls: "Електронне",
    },
    isHit: true,
    relatedIds: ["mw-basic", "mw-convection"],
  },
  {
    id: "mw-convection",
    sectionId: "microwaves",
    bandId: "premium",
    brand: "Samsung / LG / Bosch",
    name: "Конвекція / міні-духовка",
    tags: ["конвекція", "випічка"],
    forWhom: "Хто хоче інколи пекти без окремої духовки",
    pros: ["Конвекція розширює сценарії", "Більше програм", "Як компактна духовка"],
    con: "Ціна; для постійної випічки краща духовка",
    upsell: ["Деко / приладдя"],
    pitch: "Конвекцію пояснюємо як «інколи запекти», не як заміну повноцінної духовки.",
    specs: {
      volume: "25–30+ л",
      power: "900+ Вт",
      mode: "Гриль + конвекція",
      controls: "Сенсор / дисплей",
    },
    isHit: true,
    relatedIds: ["mw-grill", "mw-basic"],
  },

  // VACUUMS
  {
    id: "vac-canister",
    sectionId: "vacuums",
    bandId: "budget",
    brand: "Rowenta / Bosch / Saturn",
    name: "Класичний мішок/контейнер",
    tags: ["класика", "килими"],
    forWhom: "Квартира з килимами, звичне прибирання",
    pros: ["Потужне всмоктування", "Зрозуміло всім", "Дешевше за роботів"],
    con: "Тягати за собою, кабель",
    upsell: ["Мішки / фільтри", "Насадка для меблів"],
    pitch: "Якщо є килими й хочуть «щоб тягнуло» — класика досі сильний аргумент.",
    specs: {
      type: "Класичний",
      suction: "Високе для сегмента",
      bin: "Мішок або контейнер",
      attachments: "Підлога / щілинна",
    },
    isHit: true,
    relatedIds: ["vac-stick", "vac-robot"],
  },
  {
    id: "vac-stick",
    sectionId: "vacuums",
    bandId: "mid",
    brand: "Xiaomi / Rowenta / Philips",
    name: "Вертикальний бездротовий",
    tags: ["швидко", "щодня", "без дроту"],
    forWhom: "Швидке щоденне прибирання",
    pros: ["Завжди під рукою", "Без розетки", "Зручно для твердої підлоги"],
    con: "Батарея обмежена; на великих килимах класика сильніша",
    upsell: ["Запасний фільтр", "Кріплення на стіну"],
    pitch: "Вертикаль продаємо як «прибрав за 7 хвилин після вечері», не як заміну раз на тиждень глибоко.",
    specs: {
      type: "Вертикальний",
      suction: "Середнє / добре",
      bin: "Контейнер",
      attachments: "Підлога, меблі, щілинна",
    },
    isHit: true,
    relatedIds: ["vac-canister", "vac-robot"],
  },
  {
    id: "vac-robot",
    sectionId: "vacuums",
    bandId: "premium",
    brand: "Xiaomi / RoboRock / Ecovacs",
    name: "Робот-пилосос",
    tags: ["робот", "шерсть", "авто"],
    forWhom: "Підтримка чистоти, тварини, мало часу",
    pros: ["Прибирає сам за розкладом", "Корисно з тваринами", "Економить час"],
    con: "Не завжди замінює глибоке прибирання",
    upsell: ["Змінні ганчірки / мішки станції", "Пороги/бар’єри"],
    pitch: "Робот — про підтримку чистоти щодня. Чесно кажемо, що раз на тиждень можна пройтись вертикаллю.",
    specs: {
      type: "Робот",
      suction: "Залежить від моделі",
      bin: "Контейнер / станція",
      attachments: "Карта / зони / волога",
    },
    isHit: true,
    relatedIds: ["vac-stick", "vac-canister"],
  },

  // HAIR DRYERS
  {
    id: "dryer-basic",
    sectionId: "hair-dryers",
    bandId: "budget",
    brand: "Philips / Rowenta / Vitek",
    name: "Базовий фен 1800–2100 Вт",
    tags: ["сушка", "бюджет"],
    forWhom: "Швидко висушити без складних укладок",
    pros: ["Достатня потужність", "Низька ціна", "Є концентратор"],
    con: "Гучніший, менше турботи про волосся",
    upsell: ["Термозахист (якщо є в зоні)", "Розчіска"],
    pitch: "Для простої сушки не обов’язково салонний фен — головне потужність і концентратор.",
    specs: {
      power: "1800–2100 Вт",
      speeds: "2 швидкості / 2–3 температури",
      ions: "Може не бути",
      nozzles: "Концентратор",
    },
    isHit: true,
    relatedIds: ["dryer-ions", "dryer-pro"],
  },
  {
    id: "dryer-ions",
    sectionId: "hair-dryers",
    bandId: "mid",
    brand: "Philips / Remington / BaByliss",
    name: "З іонізацією",
    tags: ["іонізація", "менше пушіння"],
    forWhom: "Регулярні укладки, хочуть менш пухке волосся",
    pros: ["Менше статички", "Приємніший результат", "Більше режимів"],
    con: "Дорожче за базовий",
    upsell: ["Дифузор якщо кучері", "Стайлер"],
    pitch: "Іонізацію пояснюємо просто: волосся менше електризується і виглядає гладше.",
    specs: {
      power: "2100–2300 Вт",
      speeds: "Кілька комбінацій",
      ions: "Так",
      nozzles: "Концентратор + інколи дифузор",
    },
    isHit: true,
    relatedIds: ["dryer-basic", "dryer-pro"],
  },
  {
    id: "dryer-pro",
    sectionId: "hair-dryers",
    bandId: "premium",
    brand: "Dyson / BaByliss Pro / Rowenta",
    name: "Преміум / салонний",
    tags: ["салон", "тихо", "швидко"],
    forWhom: "Часті укладки, хочуть швидкість і дбайливість",
    pros: ["Швидше сушить", "Кращий контроль", "Комфорт ваги/шуму у топів"],
    con: "Ціна сильно вища",
    upsell: ["Повний набір насадок", "Стайлер в комплект сценарію"],
    pitch: "Преміум фен — коли сушать і укладають часто. Інакше середній з іонами закриє потребу.",
    specs: {
      power: "Високий повітряний потік",
      speeds: "Точний контроль",
      ions: "Так",
      nozzles: "Набір насадок",
    },
    isHit: true,
    relatedIds: ["dryer-ions", "styler-multi"],
  },

  // STYLERS
  {
    id: "straightener-basic",
    sectionId: "stylers",
    bandId: "budget",
    brand: "Vitek / Philips / Rowenta",
    name: "Випрямляч базовий",
    tags: ["вирівняти", "бюджет"],
    forWhom: "Рідко вирівняти волосся",
    pros: ["Недорого", "Робить задачу", "Швидкий подарунок"],
    con: "Покриття й температура простіші",
    upsell: ["Термозахист", "Фен"],
    pitch: "Якщо вирівнюють раз на місяць — не обов’язково преміум-стайлер.",
    specs: {
      plates: "Кераміка базова",
      temp: "Фіксована / мало режимів",
      ions: "Рідко",
      attachments: "Немає",
    },
    isHit: true,
    relatedIds: ["straightener-mid", "styler-multi"],
  },
  {
    id: "straightener-mid",
    sectionId: "stylers",
    bandId: "mid",
    brand: "Philips / Remington / BaByliss",
    name: "Випрямляч з контролем температури",
    tags: ["температура", "регулярно"],
    forWhom: "Регулярні укладки вдома",
    pros: ["Можна обрати температуру під тип волосся", "Краще покриття", "Менше ризику перепалити"],
    con: "Дорожче",
    upsell: ["Фен з іонами", "Термозахист"],
    pitch: "Контроль температури — головна різниця між «просто випрямлячем» і дбайливим.",
    specs: {
      plates: "Кераміка / турмалін",
      temp: "Регульована",
      ions: "Часто є",
      attachments: "Іноді насадки",
    },
    isHit: true,
    relatedIds: ["straightener-basic", "styler-multi"],
  },
  {
    id: "styler-multi",
    sectionId: "stylers",
    bandId: "premium",
    brand: "Dyson / BaByliss / Philips",
    name: "Мультистайлер",
    tags: ["насадки", "локони", "обʼєм"],
    forWhom: "Різні укладки одним пристроєм",
    pros: ["Багато сценаріїв", "Подарунковий «вау»", "Менше окремих девайсів"],
    con: "Ціна; треба реально користуватись насадками",
    upsell: ["Фен преміум", "Кейс"],
    pitch: "Мультистайлер має сенс, якщо клієнт робить різні укладки, а не лише «вирівняти чубчик».",
    specs: {
      plates: "Залежить від насадки",
      temp: "Розумний контроль у топів",
      ions: "Так",
      attachments: "Набір (плойка, браш, вирівнювання)",
    },
    isHit: true,
    relatedIds: ["straightener-mid", "dryer-pro"],
  },

  // Lightweight stubs for remaining sections so the map feels global
  {
    id: "tablet-budget",
    sectionId: "tablets",
    bandId: "budget",
    brand: "Lenovo / Xiaomi",
    name: "Планшет для відео / дітей",
    tags: ["youtube", "діти"],
    forWhom: "Відео, мультфільми, простий веб",
    pros: ["Дешево", "Великий екран", "Легко дати дитині"],
    con: "Не для важкої роботи",
    upsell: ["Чохол-книжка", "Скло"],
    pitch: "На мультики й YouTube не обов’язково iPad.",
    specs: { display: "10–11\"", memory: "64–128 ГБ", battery: "На день+", pen: "Звичайно немає" },
    isHit: true,
    relatedIds: [],
  },
  {
    id: "watch-budget",
    sectionId: "wearables",
    bandId: "budget",
    brand: "Xiaomi / Amazfit",
    name: "Фітнес-браслет / годинник",
    tags: ["кроки", "пульс"],
    forWhom: "Спорт і сповіщення без переплати",
    pros: ["Автономність", "Ціна", "Базовий спорт"],
    con: "Менше точності й преміум-функцій",
    upsell: ["Ремінець"],
    pitch: "Якщо треба кроки й пульс — браслет часто кращий за дорогий годинник «про всяк випадок».",
    specs: { battery: "7–14 днів", sport: "Базові режими", water: "Пот / дощ", calls: "Рідко" },
    isHit: true,
    relatedIds: [],
  },
  {
    id: "acc-case",
    sectionId: "mobile-accessories",
    bandId: "mid",
    brand: "Універсал",
    name: "Чохол + скло",
    tags: ["допродаж"],
    forWhom: "Будь-який новий смартфон",
    pros: ["Захист з першого дня", "Легкий допродаж", "Клієнт рідко шкодує"],
    con: "Дешевий пластик дратує — краще нормальний середній",
    upsell: ["Powerbank", "Кабель"],
    pitch: "Телефон без чохла й скла — incomplete продаж.",
    specs: { type: "Чохол + скло", compat: "Під модель", power: "—" },
    isHit: true,
    relatedIds: [],
  },
  {
    id: "pc-office",
    sectionId: "desktops",
    bandId: "budget",
    brand: "Готовий ПК",
    name: "Офісний системник",
    tags: ["офіс", "навчання"],
    forWhom: "Документи, браузер, навчання вдома",
    pros: ["Дешевше апгрейдити", "Монітор окремо під задачу", "Тихо для офісу"],
    con: "Займає місце, не портативний",
    upsell: ["Монітор", "Клавіатура+миша"],
    pitch: "Якщо не носять із собою — ПК часто дає більше потужності за ті ж гроші.",
    specs: { cpu: "Базовий", gpu: "Вбудована", ram: "8–16 ГБ", storage: "SSD 512" },
    isHit: true,
    relatedIds: [],
  },
  {
    id: "monitor-office",
    sectionId: "monitors",
    bandId: "budget",
    brand: "Philips / Xiaomi / Acer",
    name: "24–27\" Full HD офіс",
    tags: ["офіс", "навчання"],
    forWhom: "Робота й навчання",
    pros: ["Комфортна діагональ", "Не переплачують за 160 Гц", "Легкий вибір"],
    con: "Не для кіберспорту",
    upsell: ["HDMI кабель", "Кріплення"],
    pitch: "Для Excel і Zoom 1080p 27\" часто ідеальна точка.",
    specs: { size: "24–27\"", res: "Full HD", hz: "75–100", panel: "IPS" },
    isHit: true,
    relatedIds: [],
  },
  {
    id: "peri-set",
    sectionId: "peripherals",
    bandId: "budget",
    brand: "Logitech / Xiaomi",
    name: "Комплект клава+миша",
    tags: ["допродаж"],
    forWhom: "До ноута чи ПК",
    pros: ["Зручніше за клаву ноута", "Дешево", "Швидкий допродаж"],
    con: "Ігрові фічі не потрібні всім",
    upsell: ["Килимок", "Гарнітура"],
    pitch: "Після ноута завжди питай: «Миша потрібна одразу?»",
    specs: { type: "Комплект", conn: "USB / BT", feature: "Базовий комфорт" },
    isHit: true,
    relatedIds: [],
  },
  {
    id: "soundbar-basic",
    sectionId: "soundbars",
    bandId: "budget",
    brand: "Xiaomi / Hisense / Samsung",
    name: "Саундбар стартовий",
    tags: ["тв", "звук"],
    forWhom: "Покращити звук ТВ",
    pros: ["Одразу краще за динаміки ТВ", "Просте підключення", "Недорогий апгрейд"],
    con: "Без саба бас слабший",
    upsell: ["HDMI / optical кабель"],
    pitch: "Після ТВ середнього+ сегмента саундбар — найприємніший апгрейд.",
    specs: { channels: "2.0 / 2.1", power: "Достатня для кімнати", sub: "Опційно" },
    isHit: true,
    relatedIds: [],
  },
  {
    id: "headphones-anc",
    sectionId: "headphones",
    bandId: "mid",
    brand: "Sony / Anker / Xiaomi",
    name: "ANC навушники / TWS",
    tags: ["anc", "дорога", "офіс"],
    forWhom: "Дорога, офіс, концентрація",
    pros: ["Шумодав міняє досвід", "Зручні дзвінки", "Автономність"],
    con: "Посадка індивідуальна — дай приміряти якщо можна",
    upsell: ["Чохол", "Гарантія"],
    pitch: "ANC продаємо сценарієм: метро, опенспейс, літак — не «є галочка ANC».",
    specs: { type: "TWS / накладні", anc: "Так", battery: "20–40 год з кейсом", fit: "Критично" },
    isHit: true,
    relatedIds: [],
  },
  {
    id: "dryer-machine",
    sectionId: "dryers",
    bandId: "mid",
    brand: "Samsung / LG / Beko",
    name: "Сушильна з тепловим насосом",
    tags: ["сушка", "пара до пралки"],
    forWhom: "Немає де сушити / велика сім’я",
    pros: ["Економить час і радіатори", "Дбайливіше з тепловим насосом", "Добре в парі з пралкою"],
    con: "Місце й бюджет",
    upsell: ["Колонна установка", "Підключення"],
    pitch: "Сушилку продаємо часом і відсутністю вологи в квартирі.",
    specs: { load: "7–9 кг", type: "Конденсаційна", heatpump: "Бажано так" },
    isHit: true,
    relatedIds: [],
  },
  {
    id: "dishwasher-mid",
    sectionId: "dishwashers",
    bandId: "mid",
    brand: "Bosch / Beko / Electrolux",
    name: "60 см на 12–14 комплектів",
    tags: ["сімʼя", "вода"],
    forWhom: "Сім’я, яка хоче менше мити руками",
    pros: ["Економія води й часу", "Гігієна", "Щоденна зручність"],
    con: "Треба місце й підключення",
    upsell: ["Сіль / ополіскувач", "Підключення"],
    pitch: "Посудомийку пояснюємо економією годин на тиждень, не «ще одна техніка».",
    specs: { sets: "12–14", install: "Окрема / вбудова", water: "Низька витрата", noise: "Тихі моделі кращі" },
    isHit: true,
    relatedIds: [],
  },
  {
    id: "oven-mid",
    sectionId: "cooking",
    bandId: "mid",
    brand: "Gorenje / Electrolux / Bosch",
    name: "Духовка з конвекцією",
    tags: ["випічка", "конвекція"],
    forWhom: "Готують і печуть регулярно",
    pros: ["Рівномірний жар", "Більше рецептів", "Зручні режими"],
    con: "Важливі виміри ніші",
    upsell: ["Деко", "Витяжка в тон"],
    pitch: "Конвекція — головна різниця між «просто духовкою» і зручною.",
    specs: { fuel: "Електро", volume: "60–70 л", functions: "Конвекція / гриль" },
    isHit: true,
    relatedIds: [],
  },
  {
    id: "hood-mid",
    sectionId: "hoods",
    bandId: "mid",
    brand: "Eleyus / Faber / Bosch",
    name: "Витяжка під 60–90 см",
    tags: ["кухня", "запах"],
    forWhom: "Кухня з активним готуванням",
    pros: ["Забирає запахи й жир", "Важлива ширина під поверхню", "Тихі моделі приємніші"],
    con: "Шум на максимумі",
    upsell: ["Фільтри", "Монтаж"],
    pitch: "Спочатку ширина й відвід/рециркуляція, потім дизайн.",
    specs: { width: "60–90 см", power: "Під кухню", noise: "Дивись дБ" },
    isHit: true,
    relatedIds: [],
  },
  {
    id: "heater-mid",
    sectionId: "heaters",
    bandId: "mid",
    brand: "Ballu / Timberk / Electrolux",
    name: "Обігрівач для кімнати",
    tags: ["зима", "кімната"],
    forWhom: "Догрів кімнати в сезон",
    pros: ["Швидкий ефект", "Різні типи під задачу", "Мобільність"],
    con: "Електрика = рахунок",
    upsell: ["Термостат / розумна розетка"],
    pitch: "Питай площу й чи є діти/тварини — від цього тип обігрівача.",
    specs: { type: "Конвектор / кераміка / олива", power: "1–2 кВт", safety: "Захист від перегріву" },
    isHit: true,
    relatedIds: [],
  },
  {
    id: "air-purifier",
    sectionId: "air",
    bandId: "mid",
    brand: "Xiaomi / Philips / Levoit",
    name: "Очищувач / зволожувач",
    tags: ["алергія", "сухе повітря"],
    forWhom: "Алергія, сухе повітря, дитина",
    pros: ["Помітний комфорт", "Сценарій здоров’я", "Легко пояснити"],
    con: "Фільтри треба міняти — чесно кажи",
    upsell: ["Змінний фільтр"],
    pitch: "Продаємо проблему повітря, не «ще один гаджет у розетку».",
    specs: { type: "Очищувач / зволожувач", area: "Під кімнату", filter: "HEPA / вуглець" },
    isHit: true,
    relatedIds: [],
  },
  {
    id: "coffee-caps",
    sectionId: "coffee",
    bandId: "mid",
    brand: "Philips / DeLonghi / Nespresso",
    name: "Капсульна / автоматична кава",
    tags: ["капучино", "ранок"],
    forWhom: "Смачна кава без бариста вдома",
    pros: ["Швидко", "Стабільний смак", "Подарунково"],
    con: "Ціна капсул / сервіс автомата",
    upsell: ["Капсули / засіб для очистки"],
    pitch: "Спочатку звичка: капсули, мелена чи зерна — потім модель.",
    specs: { type: "Капсульна / авто", pressure: "Еспресо-система", milk: "Капучинатор / авто" },
    isHit: true,
    relatedIds: [],
  },
  {
    id: "blender-mid",
    sectionId: "blenders",
    bandId: "mid",
    brand: "Philips / Bosch / Tefal",
    name: "Блендер / комбайн",
    tags: ["смузі", "кухня"],
    forWhom: "Смузі, суп-пюре, підготовка продуктів",
    pros: ["Економить час на кухні", "Зрозумілий допродаж", "Багато сценаріїв"],
    con: "Потужність має відповідати задачі",
    upsell: ["Чаша / ножі запасні"],
    pitch: "Питай «що саме готуватимуть» — від цього занурювальний чи стаціонар.",
    specs: { power: "600–1200 Вт", bowl: "За типом", mode: "Швидкості / пульс" },
    isHit: true,
    relatedIds: [],
  },
  {
    id: "kettle-mid",
    sectionId: "kettles",
    bandId: "mid",
    brand: "Philips / Bosch / Xiaomi",
    name: "Чайник / тостер",
    tags: ["подарунок", "кухня"],
    forWhom: "Швидкий побут і подарунки",
    pros: ["Завжди потрібні", "Легкий чек", "Дизайн вирішує"],
    con: "Переплачувати за бренд не всім треба",
    upsell: ["Чашки / набір"],
    pitch: "Тут важливі безпека, об’єм і вигляд на кухні.",
    specs: { type: "Чайник / тостер", power: "Висока", material: "Метал / скло" },
    isHit: true,
    relatedIds: [],
  },
  {
    id: "iron-mid",
    sectionId: "irons",
    bandId: "mid",
    brand: "Philips / Braun / Tefal",
    name: "Праска з хорошою парою",
    tags: ["пара", "білизна"],
    forWhom: "Регулярне прасування",
    pros: ["Пара знімає складки швидше", "Підошва ковзає", "Зрозумілий вибір"],
    con: "Для великих обсягів кращий парогенератор",
    upsell: ["Дошка", "Сітка"],
    pitch: "Дивись пару й підошву, не лише вати.",
    specs: { steam: "Сильний удар пари", sole: "Кераміка / сапфір і аналоги", tank: "Зручний об’єм" },
    isHit: true,
    relatedIds: [],
  },
  {
    id: "trimmer-mid",
    sectionId: "grooming",
    bandId: "mid",
    brand: "Philips / Braun / Xiaomi",
    name: "Тример / машинка",
    tags: ["подарунок", "догляд"],
    forWhom: "Догляд за бородою / стрижка вдома",
    pros: ["Подарунковий сегмент", "Насадки вирішують", "Автономність зручна"],
    con: "Дешеві леза тупляться швидше",
    upsell: ["Масло для лез", "Набір насадок"],
    pitch: "Питай: борода, стрижка голови чи все разом — від цього набір.",
    specs: { runtime: "60–120 хв", blades: "Насадки в комплекті", wet: "Мокро/сухо у середніх+" },
    isHit: true,
    relatedIds: [],
  },
];
