import type { Department, Section } from "./types";

export const departments: Department[] = [
  {
    id: "mobile",
    title: "Мобільні",
    blurb: "Смартфони, планшети, годинники та аксесуари",
    order: 1,
  },
  {
    id: "computers",
    title: "Комп’ютери",
    blurb: "Ноути, ПК, монітори, периферія",
    order: 2,
  },
  {
    id: "tv-audio",
    title: "ТВ і аудіо",
    blurb: "Телевізори, саундбари, навушники",
    order: 3,
  },
  {
    id: "major-appliances",
    title: "Велика побутова",
    blurb: "Холодильники, пралки, посудомийки, кухня",
    order: 4,
  },
  {
    id: "climate",
    title: "Клімат",
    blurb: "Кондиціонери, обігрів, повітря",
    order: 5,
  },
  {
    id: "small-kitchen",
    title: "Кухня МБТ",
    blurb: "Мікрохвильовки, кава, блендери",
    order: 6,
  },
  {
    id: "home-care",
    title: "Дім і прибирання",
    blurb: "Пилососи, праски, дім",
    order: 7,
  },
  {
    id: "beauty",
    title: "Краса і догляд",
    blurb: "Фени, стайлери, тримери",
    order: 8,
  },
];

export const sections: Section[] = [
  {
    id: "smartphones",
    departmentId: "mobile",
    title: "Смартфони",
    summary:
      "Клієнти майже завжди приходять із бюджетом і сценарієм: для себе, для мами, для роботи. Вчи полиці й 3 аргументи на хіт.",
    priority: true,
    compareKeys: [
      { key: "display", label: "Екран" },
      { key: "memory", label: "Пам’ять / ОЗП" },
      { key: "camera", label: "Камера" },
      { key: "battery", label: "Батарея" },
      { key: "chip", label: "Плавність" },
    ],
    priceBands: [
      {
        id: "budget",
        label: "Бюджет",
        priceFrom: 0,
        priceTo: 12000,
        forWhom: "Перший смартфон, дитина, запасний",
      },
      {
        id: "mid",
        label: "Середній",
        priceFrom: 12000,
        priceTo: 25000,
        forWhom: "Щоденне використання без зайвого",
      },
      {
        id: "premium",
        label: "Преміум",
        priceFrom: 25000,
        forWhom: "Камера, швидкість, довга підтримка",
      },
    ],
  },
  {
    id: "tablets",
    departmentId: "mobile",
    title: "Планшети",
    summary: "Для навчання, YouTube, читання й легкого малювання.",
    priority: false,
    compareKeys: [
      { key: "display", label: "Екран" },
      { key: "memory", label: "Пам’ять" },
      { key: "battery", label: "Батарея" },
      { key: "pen", label: "Стилус" },
    ],
    priceBands: [
      {
        id: "budget",
        label: "Бюджет",
        priceFrom: 0,
        priceTo: 10000,
        forWhom: "Діти, відео, прості задачі",
      },
      {
        id: "mid",
        label: "Середній",
        priceFrom: 10000,
        priceTo: 22000,
        forWhom: "Навчання і нотатки",
      },
      {
        id: "premium",
        label: "Преміум",
        priceFrom: 22000,
        forWhom: "Робота зі стилусом, якісний екран",
      },
    ],
  },
  {
    id: "wearables",
    departmentId: "mobile",
    title: "Смарт-годинники",
    summary: "Спорт, сповіщення, сон і пульс — продавай сценарій, не «гаджет заради гаджета».",
    priority: false,
    compareKeys: [
      { key: "battery", label: "Автономність" },
      { key: "sport", label: "Спорт" },
      { key: "water", label: "Водозахист" },
      { key: "calls", label: "Дзвінки" },
    ],
    priceBands: [
      {
        id: "budget",
        label: "Бюджет",
        priceFrom: 0,
        priceTo: 3000,
        forWhom: "Базовий спорт і сповіщення",
      },
      {
        id: "mid",
        label: "Середній",
        priceFrom: 3000,
        priceTo: 9000,
        forWhom: "Щоденне носіння",
      },
      {
        id: "premium",
        label: "Преміум",
        priceFrom: 9000,
        forWhom: "Екосистема й точний спорт",
      },
    ],
  },
  {
    id: "mobile-accessories",
    departmentId: "mobile",
    title: "Аксесуари мобільні",
    summary: "Допродаж майже до кожного смартфона: захист, зарядка, powerbank.",
    priority: false,
    compareKeys: [
      { key: "type", label: "Тип" },
      { key: "compat", label: "Сумісність" },
      { key: "power", label: "Потужність" },
    ],
    priceBands: [
      {
        id: "budget",
        label: "Бюджет",
        priceFrom: 0,
        priceTo: 400,
        forWhom: "Базовий захист",
      },
      {
        id: "mid",
        label: "Середній",
        priceFrom: 400,
        priceTo: 1200,
        forWhom: "Нормальний захист і зарядка",
      },
      {
        id: "premium",
        label: "Преміум",
        priceFrom: 1200,
        forWhom: "Швидка зарядка, MagSafe, бренди",
      },
    ],
  },
  {
    id: "laptops",
    departmentId: "computers",
    title: "Ноутбуки",
    summary:
      "Спочатку задача: універ / офіс / креатив / ігри. Потім бюджет. Потім 2–3 моделі.",
    priority: true,
    compareKeys: [
      { key: "cpu", label: "Процесор" },
      { key: "ram", label: "ОЗП" },
      { key: "ssd", label: "SSD" },
      { key: "display", label: "Екран" },
      { key: "battery", label: "Автономність" },
      { key: "weight", label: "Вага" },
    ],
    priceBands: [
      {
        id: "budget",
        label: "Бюджет",
        priceFrom: 0,
        priceTo: 20000,
        forWhom: "Навчання, браузер, Zoom",
      },
      {
        id: "mid",
        label: "Середній",
        priceFrom: 20000,
        priceTo: 40000,
        forWhom: "Робота щодня без гальм",
      },
      {
        id: "premium",
        label: "Преміум",
        priceFrom: 40000,
        forWhom: "Потужність, екран, мобільність",
      },
    ],
  },
  {
    id: "desktops",
    departmentId: "computers",
    title: "ПК і моноблоки",
    summary: "Стаціонар: ігри, монтаж, офіс. Питай про монітор і периферію одразу.",
    priority: false,
    compareKeys: [
      { key: "cpu", label: "CPU" },
      { key: "gpu", label: "Відеокарта" },
      { key: "ram", label: "ОЗП" },
      { key: "storage", label: "Накопичувач" },
    ],
    priceBands: [
      {
        id: "budget",
        label: "Бюджет",
        priceFrom: 0,
        priceTo: 18000,
        forWhom: "Офіс і навчання",
      },
      {
        id: "mid",
        label: "Середній",
        priceFrom: 18000,
        priceTo: 40000,
        forWhom: "Ігри Full HD / робота",
      },
      {
        id: "premium",
        label: "Преміум",
        priceFrom: 40000,
        forWhom: "Потужні ігри й креатив",
      },
    ],
  },
  {
    id: "monitors",
    departmentId: "computers",
    title: "Монітори",
    summary: "Діагональ і задача важливіші за «найбільші Герци для офісу».",
    priority: false,
    compareKeys: [
      { key: "size", label: "Діагональ" },
      { key: "res", label: "Роздільність" },
      { key: "hz", label: "Гц" },
      { key: "panel", label: "Матриця" },
    ],
    priceBands: [
      {
        id: "budget",
        label: "Бюджет",
        priceFrom: 0,
        priceTo: 5000,
        forWhom: "Офіс, навчання",
      },
      {
        id: "mid",
        label: "Середній",
        priceFrom: 5000,
        priceTo: 12000,
        forWhom: "Робота + легкі ігри",
      },
      {
        id: "premium",
        label: "Преміум",
        priceFrom: 12000,
        forWhom: "Ігри / дизайн",
      },
    ],
  },
  {
    id: "peripherals",
    departmentId: "computers",
    title: "Периферія",
    summary: "Клавіатури, миші, гарнітури — легкий допродаж до ноута й ПК.",
    priority: false,
    compareKeys: [
      { key: "type", label: "Тип" },
      { key: "conn", label: "Підключення" },
      { key: "feature", label: "Фішка" },
    ],
    priceBands: [
      {
        id: "budget",
        label: "Бюджет",
        priceFrom: 0,
        priceTo: 800,
        forWhom: "Базовий набір",
      },
      {
        id: "mid",
        label: "Середній",
        priceFrom: 800,
        priceTo: 2500,
        forWhom: "Комфорт на щодень",
      },
      {
        id: "premium",
        label: "Преміум",
        priceFrom: 2500,
        forWhom: "Ігри / механіка",
      },
    ],
  },
  {
    id: "tvs",
    departmentId: "tv-audio",
    title: "Телевізори",
    summary:
      "Спочатку кімната й діагональ, потім матриця й Smart. Не починай з Герц.",
    priority: true,
    compareKeys: [
      { key: "size", label: "Діагональ" },
      { key: "panel", label: "Матриця" },
      { key: "hz", label: "Гц / рух" },
      { key: "smart", label: "Smart TV" },
      { key: "hdmi", label: "HDMI" },
    ],
    priceBands: [
      {
        id: "budget",
        label: "Бюджет",
        priceFrom: 0,
        priceTo: 15000,
        forWhom: "Кухня, дача, перший ТВ",
      },
      {
        id: "mid",
        label: "Середній",
        priceFrom: 15000,
        priceTo: 35000,
        forWhom: "Вітальня на щодень",
      },
      {
        id: "premium",
        label: "Преміум",
        priceFrom: 35000,
        forWhom: "Кіно, спорт, темна кімната",
      },
    ],
  },
  {
    id: "soundbars",
    departmentId: "tv-audio",
    title: "Аудіо / саундбари",
    summary: "Покращує будь-який ТВ. Питай про розмір тумби й чи потрібен саб.",
    priority: false,
    compareKeys: [
      { key: "channels", label: "Канали" },
      { key: "power", label: "Потужність" },
      { key: "sub", label: "Сабвуфер" },
    ],
    priceBands: [
      {
        id: "budget",
        label: "Бюджет",
        priceFrom: 0,
        priceTo: 4000,
        forWhom: "Просто гучніше й чистіше",
      },
      {
        id: "mid",
        label: "Середній",
        priceFrom: 4000,
        priceTo: 12000,
        forWhom: "Фільми з басом",
      },
      {
        id: "premium",
        label: "Преміум",
        priceFrom: 12000,
        forWhom: "Домашній кінотеатр",
      },
    ],
  },
  {
    id: "headphones",
    departmentId: "tv-audio",
    title: "Навушники",
    summary: "ANC, посадка й автономність — три питання, які закривають 80% вибору.",
    priority: false,
    compareKeys: [
      { key: "type", label: "Тип" },
      { key: "anc", label: "Шумодав" },
      { key: "battery", label: "Автономність" },
      { key: "fit", label: "Посадка" },
    ],
    priceBands: [
      {
        id: "budget",
        label: "Бюджет",
        priceFrom: 0,
        priceTo: 1500,
        forWhom: "Музика й дзвінки",
      },
      {
        id: "mid",
        label: "Середній",
        priceFrom: 1500,
        priceTo: 5000,
        forWhom: "Дорога / офіс з ANC",
      },
      {
        id: "premium",
        label: "Преміум",
        priceFrom: 5000,
        forWhom: "Максимальний комфорт",
      },
    ],
  },
  {
    id: "fridges",
    departmentId: "major-appliances",
    title: "Холодильники",
    summary: "Об’єм під сім’ю, No Frost, розмір ніші. Виміри важливіші за бренд.",
    priority: true,
    compareKeys: [
      { key: "volume", label: "Об’єм" },
      { key: "frost", label: "Розморозка" },
      { key: "energy", label: "Енергоклас" },
      { key: "zones", label: "Зони" },
      { key: "noise", label: "Шум" },
    ],
    priceBands: [
      {
        id: "budget",
        label: "Бюджет",
        priceFrom: 0,
        priceTo: 16000,
        forWhom: "1–2 особи, оренда",
      },
      {
        id: "mid",
        label: "Середній",
        priceFrom: 16000,
        priceTo: 32000,
        forWhom: "Сім’я, No Frost",
      },
      {
        id: "premium",
        label: "Преміум",
        priceFrom: 32000,
        forWhom: "Великий об’єм, зони, тиша",
      },
    ],
  },
  {
    id: "washers",
    departmentId: "major-appliances",
    title: "Пральні машини",
    summary: "Кг завантаження + інвертор + оберти. Для сім’ї з 3+ майже завжди 7–9 кг.",
    priority: true,
    compareKeys: [
      { key: "load", label: "Завантаження" },
      { key: "type", label: "Тип" },
      { key: "rpm", label: "Оберти" },
      { key: "inverter", label: "Інвертор" },
      { key: "programs", label: "Програми" },
    ],
    priceBands: [
      {
        id: "budget",
        label: "Бюджет",
        priceFrom: 0,
        priceTo: 15000,
        forWhom: "1–2 особи, базові програми",
      },
      {
        id: "mid",
        label: "Середній",
        priceFrom: 15000,
        priceTo: 28000,
        forWhom: "Сім’я, інвертор, тихіше",
      },
      {
        id: "premium",
        label: "Преміум",
        priceFrom: 28000,
        forWhom: "Велике завантаження, пар, тиша",
      },
    ],
  },
  {
    id: "dryers",
    departmentId: "major-appliances",
    title: "Сушильні машини",
    summary: "Часто беруть у парі з пралкою. Питай про місце й вентиляцію/конденсат.",
    priority: false,
    compareKeys: [
      { key: "load", label: "Завантаження" },
      { key: "type", label: "Тип сушки" },
      { key: "heatpump", label: "Тепловий насос" },
    ],
    priceBands: [
      {
        id: "budget",
        label: "Бюджет",
        priceFrom: 0,
        priceTo: 20000,
        forWhom: "Базова сушка",
      },
      {
        id: "mid",
        label: "Середній",
        priceFrom: 20000,
        priceTo: 35000,
        forWhom: "Економніше й дбайливіше",
      },
      {
        id: "premium",
        label: "Преміум",
        priceFrom: 35000,
        forWhom: "Тихо, ефективно, багато програм",
      },
    ],
  },
  {
    id: "dishwashers",
    departmentId: "major-appliances",
    title: "Посудомийні",
    summary: "Кількість комплектів і тип вбудови. Економія води — сильний аргумент.",
    priority: false,
    compareKeys: [
      { key: "sets", label: "Комплектів" },
      { key: "install", label: "Вбудова" },
      { key: "water", label: "Витрата води" },
      { key: "noise", label: "Шум" },
    ],
    priceBands: [
      {
        id: "budget",
        label: "Бюджет",
        priceFrom: 0,
        priceTo: 14000,
        forWhom: "Компакт / старт",
      },
      {
        id: "mid",
        label: "Середній",
        priceFrom: 14000,
        priceTo: 26000,
        forWhom: "Сім’я на щодень",
      },
      {
        id: "premium",
        label: "Преміум",
        priceFrom: 26000,
        forWhom: "Тихо, гнучкі кошики",
      },
    ],
  },
  {
    id: "cooking",
    departmentId: "major-appliances",
    title: "Плити й духовки",
    summary: "Газ/електро, розмір ніші, функції гриля й конвекції.",
    priority: false,
    compareKeys: [
      { key: "fuel", label: "Тип" },
      { key: "volume", label: "Об’єм" },
      { key: "functions", label: "Функції" },
    ],
    priceBands: [
      {
        id: "budget",
        label: "Бюджет",
        priceFrom: 0,
        priceTo: 10000,
        forWhom: "Бадове готування",
      },
      {
        id: "mid",
        label: "Середній",
        priceFrom: 10000,
        priceTo: 22000,
        forWhom: "Конвекція, зручність",
      },
      {
        id: "premium",
        label: "Преміум",
        priceFrom: 22000,
        forWhom: "Піроліз, точний контроль",
      },
    ],
  },
  {
    id: "hoods",
    departmentId: "major-appliances",
    title: "Витяжки",
    summary: "Ширина під поверхню, продуктивність і шум.",
    priority: false,
    compareKeys: [
      { key: "width", label: "Ширина" },
      { key: "power", label: "Продуктивність" },
      { key: "noise", label: "Шум" },
    ],
    priceBands: [
      {
        id: "budget",
        label: "Бюджет",
        priceFrom: 0,
        priceTo: 4000,
        forWhom: "Невелика кухня",
      },
      {
        id: "mid",
        label: "Середній",
        priceFrom: 4000,
        priceTo: 10000,
        forWhom: "Тихіше й сильніше",
      },
      {
        id: "premium",
        label: "Преміум",
        priceFrom: 10000,
        forWhom: "Дизайн і тиша",
      },
    ],
  },
  {
    id: "acs",
    departmentId: "climate",
    title: "Кондиціонери",
    summary: "Площа кімнати → BTU. Інвертор майже завжди кращий аргумент для дому.",
    priority: true,
    compareKeys: [
      { key: "area", label: "Площа / BTU" },
      { key: "inverter", label: "Інвертор" },
      { key: "energy", label: "Енергоклас" },
      { key: "noise", label: "Шум" },
      { key: "wifi", label: "Wi‑Fi" },
    ],
    priceBands: [
      {
        id: "budget",
        label: "Бюджет",
        priceFrom: 0,
        priceTo: 18000,
        forWhom: "Невелика кімната",
      },
      {
        id: "mid",
        label: "Середній",
        priceFrom: 18000,
        priceTo: 32000,
        forWhom: "Дім, інвертор, тихіше",
      },
      {
        id: "premium",
        label: "Преміум",
        priceFrom: 32000,
        forWhom: "Тиша, Wi‑Fi, якісний монтаж-сегмент",
      },
    ],
  },
  {
    id: "heaters",
    departmentId: "climate",
    title: "Обігрівачі",
    summary: "Тип обігріву й безпека важливіші за «найбільші вати».",
    priority: false,
    compareKeys: [
      { key: "type", label: "Тип" },
      { key: "power", label: "Потужність" },
      { key: "safety", label: "Безпека" },
    ],
    priceBands: [
      {
        id: "budget",
        label: "Бюджет",
        priceFrom: 0,
        priceTo: 1200,
        forWhom: "Точковий обігрів",
      },
      {
        id: "mid",
        label: "Середній",
        priceFrom: 1200,
        priceTo: 3500,
        forWhom: "Кімната на щодень",
      },
      {
        id: "premium",
        label: "Преміум",
        priceFrom: 3500,
        forWhom: "Тихо / розумний контроль",
      },
    ],
  },
  {
    id: "air",
    departmentId: "climate",
    title: "Повітря",
    summary: "Зволожувачі, очищувачі, вентилятори — продавай проблему клієнта.",
    priority: false,
    compareKeys: [
      { key: "type", label: "Тип" },
      { key: "area", label: "Площа" },
      { key: "filter", label: "Фільтр" },
    ],
    priceBands: [
      {
        id: "budget",
        label: "Бюджет",
        priceFrom: 0,
        priceTo: 1500,
        forWhom: "Базовий комфорт",
      },
      {
        id: "mid",
        label: "Середній",
        priceFrom: 1500,
        priceTo: 5000,
        forWhom: "Регулярне використання",
      },
      {
        id: "premium",
        label: "Преміум",
        priceFrom: 5000,
        forWhom: "Алергія / велика площа",
      },
    ],
  },
  {
    id: "microwaves",
    departmentId: "small-kitchen",
    title: "Мікрохвильовки",
    summary: "Літри під сім’ю, гриль/конвекція якщо печуть більше ніж гріють.",
    priority: true,
    compareKeys: [
      { key: "volume", label: "Об’єм" },
      { key: "power", label: "Потужність" },
      { key: "mode", label: "Гриль / конвекція" },
      { key: "controls", label: "Керування" },
    ],
    priceBands: [
      {
        id: "budget",
        label: "Бюджет",
        priceFrom: 0,
        priceTo: 3000,
        forWhom: "Підігрів і розморозка",
      },
      {
        id: "mid",
        label: "Середній",
        priceFrom: 3000,
        priceTo: 7000,
        forWhom: "Гриль, зручні програми",
      },
      {
        id: "premium",
        label: "Преміум",
        priceFrom: 7000,
        forWhom: "Конвекція, як міні-духовка",
      },
    ],
  },
  {
    id: "coffee",
    departmentId: "small-kitchen",
    title: "Кава",
    summary: "Капсульна / крапельна / автоматична — спочатку звичка клієнта.",
    priority: false,
    compareKeys: [
      { key: "type", label: "Тип" },
      { key: "pressure", label: "Тиск / спосіб" },
      { key: "milk", label: "Молоко" },
    ],
    priceBands: [
      {
        id: "budget",
        label: "Бюджет",
        priceFrom: 0,
        priceTo: 2500,
        forWhom: "Проста кава вдома",
      },
      {
        id: "mid",
        label: "Середній",
        priceFrom: 2500,
        priceTo: 9000,
        forWhom: "Капучино без танців",
      },
      {
        id: "premium",
        label: "Преміум",
        priceFrom: 9000,
        forWhom: "Автомат на щодень",
      },
    ],
  },
  {
    id: "blenders",
    departmentId: "small-kitchen",
    title: "Блендери / комбайни",
    summary: "Потужність і чаша під задачу: смузі, суп, фарш.",
    priority: false,
    compareKeys: [
      { key: "power", label: "Потужність" },
      { key: "bowl", label: "Чаша" },
      { key: "mode", label: "Режими" },
    ],
    priceBands: [
      {
        id: "budget",
        label: "Бюджет",
        priceFrom: 0,
        priceTo: 1200,
        forWhom: "Рідко / просто",
      },
      {
        id: "mid",
        label: "Середній",
        priceFrom: 1200,
        priceTo: 4000,
        forWhom: "Регулярно на кухні",
      },
      {
        id: "premium",
        label: "Преміум",
        priceFrom: 4000,
        forWhom: "Потужно й довговічно",
      },
    ],
  },
  {
    id: "kettles",
    departmentId: "small-kitchen",
    title: "Чайники / тостери",
    summary: "Швидкі подарунки й допродаж. Матеріал корпусу й безпека.",
    priority: false,
    compareKeys: [
      { key: "type", label: "Тип" },
      { key: "power", label: "Потужність" },
      { key: "material", label: "Матеріал" },
    ],
    priceBands: [
      {
        id: "budget",
        label: "Бюджет",
        priceFrom: 0,
        priceTo: 800,
        forWhom: "Базовий функціонал",
      },
      {
        id: "mid",
        label: "Середній",
        priceFrom: 800,
        priceTo: 2000,
        forWhom: "Зручність і вигляд",
      },
      {
        id: "premium",
        label: "Преміум",
        priceFrom: 2000,
        forWhom: "Температура / дизайн",
      },
    ],
  },
  {
    id: "vacuums",
    departmentId: "home-care",
    title: "Пилососи",
    summary: "Класика / вертикальний / робот. Спочатку тип підлоги й чи є тварини.",
    priority: true,
    compareKeys: [
      { key: "type", label: "Тип" },
      { key: "suction", label: "Всмоктування" },
      { key: "bin", label: "Контейнер" },
      { key: "attachments", label: "Насадки" },
    ],
    priceBands: [
      {
        id: "budget",
        label: "Бюджет",
        priceFrom: 0,
        priceTo: 4000,
        forWhom: "Базове прибирання",
      },
      {
        id: "mid",
        label: "Середній",
        priceFrom: 4000,
        priceTo: 12000,
        forWhom: "Зручно на щодень",
      },
      {
        id: "premium",
        label: "Преміум",
        priceFrom: 12000,
        forWhom: "Роботи / преміум-вертикалі",
      },
    ],
  },
  {
    id: "irons",
    departmentId: "home-care",
    title: "Праски / пар",
    summary: "Потужність пари й підошва. Парогенератор — для великого обсягу білизни.",
    priority: false,
    compareKeys: [
      { key: "steam", label: "Пара" },
      { key: "sole", label: "Підошва" },
      { key: "tank", label: "Бак" },
    ],
    priceBands: [
      {
        id: "budget",
        label: "Бюджет",
        priceFrom: 0,
        priceTo: 1000,
        forWhom: "Рідко гладити",
      },
      {
        id: "mid",
        label: "Середній",
        priceFrom: 1000,
        priceTo: 3500,
        forWhom: "Сім’я щотижня",
      },
      {
        id: "premium",
        label: "Преміум",
        priceFrom: 3500,
        forWhom: "Парогенератор / багато пари",
      },
    ],
  },
  {
    id: "hair-dryers",
    departmentId: "beauty",
    title: "Фени",
    summary: "Потужність, іонізація, насадки. Для дівчат часто вирішує вага й шум.",
    priority: true,
    compareKeys: [
      { key: "power", label: "Потужність" },
      { key: "speeds", label: "Режими" },
      { key: "ions", label: "Іонізація" },
      { key: "nozzles", label: "Насадки" },
    ],
    priceBands: [
      {
        id: "budget",
        label: "Бюджет",
        priceFrom: 0,
        priceTo: 1500,
        forWhom: "Базова сушка",
      },
      {
        id: "mid",
        label: "Середній",
        priceFrom: 1500,
        priceTo: 5000,
        forWhom: "Дбайливіше й швидше",
      },
      {
        id: "premium",
        label: "Преміум",
        priceFrom: 5000,
        forWhom: "Салонний результат удома",
      },
    ],
  },
  {
    id: "stylers",
    departmentId: "beauty",
    title: "Випрямлячі / стайлери",
    summary: "Покриття пластин і температура. Стайлер — про насадки й сценарії укладки.",
    priority: true,
    compareKeys: [
      { key: "plates", label: "Покриття" },
      { key: "temp", label: "Температура" },
      { key: "ions", label: "Іонізація" },
      { key: "attachments", label: "Насадки" },
    ],
    priceBands: [
      {
        id: "budget",
        label: "Бюджет",
        priceFrom: 0,
        priceTo: 1500,
        forWhom: "Рідкі укладки",
      },
      {
        id: "mid",
        label: "Середній",
        priceFrom: 1500,
        priceTo: 5000,
        forWhom: "Регулярно, дбайливіше",
      },
      {
        id: "premium",
        label: "Преміум",
        priceFrom: 5000,
        forWhom: "Мультистайлер / бренд",
      },
    ],
  },
  {
    id: "grooming",
    departmentId: "beauty",
    title: "Стрижка / тримери",
    summary: "Насадки, автономність, мокро/сухо. Часто подарунковий сегмент.",
    priority: false,
    compareKeys: [
      { key: "runtime", label: "Автономність" },
      { key: "blades", label: "Леза / насадки" },
      { key: "wet", label: "Мокро / сухо" },
    ],
    priceBands: [
      {
        id: "budget",
        label: "Бюджет",
        priceFrom: 0,
        priceTo: 1000,
        forWhom: "Базовий догляд",
      },
      {
        id: "mid",
        label: "Середній",
        priceFrom: 1000,
        priceTo: 3500,
        forWhom: "Зручний щоденний набір",
      },
      {
        id: "premium",
        label: "Преміум",
        priceFrom: 3500,
        forWhom: "Точність і комплект",
      },
    ],
  },
];
