import type { Scenario, Term, TrainerStep } from "./types";

export const terms: Term[] = [
  {
    id: "t-amoled",
    sectionId: "smartphones",
    title: "AMOLED",
    plainExplain:
      "Екран з глибоким чорним і контрастом. Картинка «соковитіша», особливо ввечері. У середньому+ сегменті це сильний аргумент.",
  },
  {
    id: "t-ram-phone",
    sectionId: "smartphones",
    title: "ОЗП у телефоні",
    plainExplain:
      "Скільки додатків може «висіти» без перезавантаження. Для щодня комфортно від 6–8 ГБ у середньому сегменті.",
  },
  {
    id: "t-updates",
    sectionId: "smartphones",
    title: "Оновлення системи",
    plainExplain:
      "Як довго виробник підкидає нові версії Android/iOS і безпеку. Apple і Google/Samsung у середньому+ зазвичай сильніші тут.",
  },
  {
    id: "t-ram-laptop",
    sectionId: "laptops",
    title: "8 vs 16 ГБ ОЗП",
    plainExplain:
      "8 ГБ — мінімум для навчання. 16 ГБ — щоб Chrome + Zoom + документи не перетворювались на слайд-шоу.",
  },
  {
    id: "t-ssd",
    sectionId: "laptops",
    title: "SSD",
    plainExplain:
      "Швидкий накопичувач. Ноут зі SSD вмикається й відкриває файли помітно швидше за старий HDD.",
  },
  {
    id: "t-igpu",
    sectionId: "laptops",
    title: "Вбудована vs дискретна відеокарта",
    plainExplain:
      "Вбудована — офіс, навчання, серіали. Дискретна — ігри, монтаж, 3D. Не продавай ігрову «про запас».",
  },
  {
    id: "t-panel-tv",
    sectionId: "tvs",
    title: "LCD / QLED / OLED",
    plainExplain:
      "LCD — база. QLED — яскравіше вдень. OLED — найкращий чорний і кіно ввечері. Підказуй від освітлення кімнати.",
  },
  {
    id: "t-hz-tv",
    sectionId: "tvs",
    title: "60 vs 120 Гц",
    plainExplain:
      "Більше Герц — плавніший рух у спорті й іграх. Для звичайних серіалів різниця менша, ніж у діагоналі й матриці.",
  },
  {
    id: "t-diag",
    sectionId: "tvs",
    title: "Діагональ і відстань",
    plainExplain:
      "Чим далі диван — тим більший ТВ можна брати. На кухню 43\" часто ок, у вітальню частіше дивляться 55\".",
  },
  {
    id: "t-nofrost",
    sectionId: "fridges",
    title: "No Frost",
    plainExplain:
      "Не треба вручну розморожувати. Для сім’ї це один із найсильніших аргументів середнього сегмента.",
  },
  {
    id: "t-fridge-volume",
    sectionId: "fridges",
    title: "Об’єм літрів",
    plainExplain:
      "1–2 особи можуть взяти менше. Сім’я з дітьми — орієнтуйся на більший холодильник і зручні полиці, не лише «гарний колір».",
  },
  {
    id: "t-inverter-wash",
    sectionId: "washers",
    title: "Інверторний двигун",
    plainExplain:
      "Тихіше, менше вібрацій, ресурс зазвичай кращий. Пояснюй як комфорт і довговічність, не як магічне слово.",
  },
  {
    id: "t-load-kg",
    sectionId: "washers",
    title: "Кг завантаження",
    plainExplain:
      "Скільки сухої білизни влазить. Для сім’ї з 3+ майже завжди комфортніше 7–9 кг, ніж «дешева 5 кг».",
  },
  {
    id: "t-btu",
    sectionId: "acs",
    title: "BTU / площа",
    plainExplain:
      "Потужність під кімнату. 09 ≈ невелика кімната, 12 — типова житлова, 18 — більша. Краще правильно, ніж «з запасом і гучно».",
  },
  {
    id: "t-inverter-ac",
    sectionId: "acs",
    title: "Інверторний кондиціонер",
    plainExplain:
      "Тримає температуру рівніше, менше вмикається/вимикається, зазвичай тихіший і економніший у довгій перспективі.",
  },
  {
    id: "t-mw-modes",
    sectionId: "microwaves",
    title: "Соло / гриль / конвекція",
    plainExplain:
      "Соло — гріти. Гриль — підрум’янити. Конвекція — інколи пекти як у міні-духовці. Не апсейли зайве.",
  },
  {
    id: "t-vac-types",
    sectionId: "vacuums",
    title: "Класика / вертикаль / робот",
    plainExplain:
      "Класика — потужно й дешево. Вертикаль — швидко щодня. Робот — підтримка чистоти сама по собі.",
  },
  {
    id: "t-ions",
    sectionId: "hair-dryers",
    title: "Іонізація",
    plainExplain:
      "Менше статичної електрики, волосся виглядає гладшим. Добре заходить у середньому сегменті фенів і стайлерів.",
  },
  {
    id: "t-temp-plates",
    sectionId: "stylers",
    title: "Контроль температури",
    plainExplain:
      "Можна обрати нагрев під тип волосся. Це головна різниця між базовим випрямлячем і дбайливішим середнім.",
  },
];

export const scenarios: Scenario[] = [
  {
    id: "sc-phone-mom",
    sectionId: "smartphones",
    clientPhrase: "Телефон мамі, щоб не складний, до 12 тисяч",
    budgetHint: "Бюджетна полиця",
    recommendedProductIds: ["phone-samsung-a", "phone-redmi-a", "phone-moto-g"],
    coachTip: "Питай: месенджери, камера для онуків, чи великий екран. Не пхай ігровий POCO.",
  },
  {
    id: "sc-phone-photo",
    sectionId: "smartphones",
    clientPhrase: "Хочу щоб фото були гарні, бюджет середній",
    budgetHint: "Середній / низ преміуму",
    recommendedProductIds: ["phone-pixel-a", "phone-samsung-a3", "phone-samsung-s"],
    coachTip: "Уточни: фото людей, вечір, відео. Pixel/Samsung часто сильніші в розмові про камеру.",
  },
  {
    id: "sc-laptop-uni",
    sectionId: "laptops",
    clientPhrase: "Ноут в універ, Zoom і пари, до 20–25к",
    budgetHint: "Бюджет / низ середнього",
    recommendedProductIds: ["laptop-office-budget", "laptop-student-mid"],
    coachTip: "Тисни на 16 ГБ якщо бюджет дозволяє. Ігровий не пропонуй «про запас».",
  },
  {
    id: "sc-laptop-travel",
    sectionId: "laptops",
    clientPhrase: "Ношу щодня, хочу легкий і з батареєю",
    budgetHint: "Середній / преміум",
    recommendedProductIds: ["laptop-ultrabook-mid", "laptop-macbook"],
    coachTip: "Вага й автономність важливіші за діагональ 15.6\".",
  },
  {
    id: "sc-tv-living",
    sectionId: "tvs",
    clientPhrase: "ТВ у вітальню, диван десь на 2.5–3 метри",
    budgetHint: "Середній",
    recommendedProductIds: ["tv-50-mid", "tv-55-mid", "tv-55-qled"],
    coachTip: "Спочатку діагональ і світло в кімнаті, потім матриця. Запропонуй саундбар.",
  },
  {
    id: "sc-tv-movies",
    sectionId: "tvs",
    clientPhrase: "Хочу як у кіно, дивимось ввечері",
    budgetHint: "Преміум",
    recommendedProductIds: ["tv-55-oled", "tv-55-qled"],
    coachTip: "Темна кімната → OLED. Світла з вікнами → QLED може бути практичніший.",
  },
  {
    id: "sc-wash-family",
    sectionId: "washers",
    clientPhrase: "Пралка для сім’ї з дитиною",
    budgetHint: "Середній",
    recommendedProductIds: ["washer-7-inv", "washer-8-9"],
    coachTip: "7–8 кг + інвертор. Поясни тишу й об’єм постілі.",
  },
  {
    id: "sc-fridge-rent",
    sectionId: "fridges",
    clientPhrase: "Холодильник на оренду, невелика кухня",
    budgetHint: "Бюджет",
    recommendedProductIds: ["fridge-small", "fridge-narrow"],
    coachTip: "Виміри ніші важливіші за бренд. Не продавай величезний No Frost «на виріст».",
  },
  {
    id: "sc-ac-sleep",
    sectionId: "acs",
    clientPhrase: "Кондиціонер у спальню, щоб не ревів",
    budgetHint: "Середній",
    recommendedProductIds: ["ac-12-inv", "ac-09"],
    coachTip: "Інвертор + правильний BTU під площу. Монтаж обговори одразу.",
  },
  {
    id: "sc-mw-heat",
    sectionId: "microwaves",
    clientPhrase: "Мікро downstreamка тільки гріти їжу",
    budgetHint: "Бюджет",
    recommendedProductIds: ["mw-basic", "mw-grill"],
    coachTip: "Не апсейли конвекцію без потреби. 20 л соло часто ідеально.",
  },
  {
    id: "sc-vac-cat",
    sectionId: "vacuums",
    clientPhrase: "Кіт линяє, хочу менше прибирати",
    budgetHint: "Середній / преміум",
    recommendedProductIds: ["vac-robot", "vac-stick", "vac-canister"],
    coachTip: "Робот на підтримку + чесно скажи про глибоке прибирання раз на тиждень.",
  },
  {
    id: "sc-dryer-gift",
    sectionId: "hair-dryers",
    clientPhrase: "Фен дівчині, щоб волосся менше пушилось",
    budgetHint: "Середній",
    recommendedProductIds: ["dryer-ions", "dryer-pro"],
    coachTip: "Іонізація + насадки. Уточни довжину волосся й чи потрібен дифузор.",
  },
  {
    id: "sc-styler",
    sectionId: "stylers",
    clientPhrase: "Хочу і вирівняти, і локони одним",
    budgetHint: "Преміум / верх середнього",
    recommendedProductIds: ["styler-multi", "straightener-mid"],
    coachTip: "Якщо реально різні укладки — мультистайлер. Якщо лише вирівняти — середній випрямляч.",
  },
];

function quiz(
  sectionId: string,
  id: string,
  title: string,
  question: string,
  options: { id: string; label: string; correct?: boolean }[],
  explain: string,
): TrainerStep {
  return {
    id,
    sectionId,
    type: "quiz",
    title,
    body: question,
    quiz: { question, options, explain },
  };
}

export const trainerSteps: TrainerStep[] = [
  // SMARTPHONES
  {
    id: "tr-phone-intro",
    sectionId: "smartphones",
    type: "intro",
    title: "Смартфони: як думати",
    body: "Спочатку сценарій і бюджет, потім 2–3 моделі з різних полиць. Не починай з характеристик.",
  },
  {
    id: "tr-phone-term-1",
    sectionId: "smartphones",
    type: "term",
    title: "Термін",
    body: "Прочитай і запам’ятай простими словами.",
    termId: "t-amoled",
  },
  {
    id: "tr-phone-term-2",
    sectionId: "smartphones",
    type: "term",
    title: "Термін",
    body: "Це допоможе пояснювати різницю середнього й бюджету.",
    termId: "t-ram-phone",
  },
  {
    id: "tr-phone-band",
    sectionId: "smartphones",
    type: "band",
    title: "Три полиці",
    body: "Бюджет — просто й зрозуміло. Середній — щодня без болю. Преміум — камера, швидкість, екосистема.",
  },
  {
    id: "tr-phone-p1",
    sectionId: "smartphones",
    type: "product",
    title: "Хіт бюджету",
    body: "Навчись говорити це вголос.",
    productId: "phone-samsung-a",
  },
  {
    id: "tr-phone-p2",
    sectionId: "smartphones",
    type: "product",
    title: "Хіт середнього",
    body: "Універсальна відповідь на «щоб і камера, і не гальмував».",
    productId: "phone-samsung-a3",
  },
  {
    id: "tr-phone-compare",
    sectionId: "smartphones",
    type: "compare",
    title: "Порівняй",
    body: "Знайди різницю «людською» мовою.",
    compareIds: ["phone-redmi-note", "phone-samsung-a3"],
  },
  {
    id: "tr-phone-sc",
    sectionId: "smartphones",
    type: "scenario",
    title: "Клиент сказав",
    body: "Обери логіку відповіді.",
    scenarioId: "sc-phone-mom",
  },
  quiz(
    "smartphones",
    "tr-phone-q1",
    "Квіз",
    "Клієнт: «мамі до 12к, щоб не складний». Що логічніше?",
    [
      { id: "a", label: "Ігровий POCO з максимумом Гц" },
      { id: "b", label: "Простий Samsung/Redmi/Moto з бюджетної полиці", correct: true },
      { id: "c", label: "Одразу флагман «щоб надовго»" },
    ],
    "Для мами важливі простота й звичність, не ігровий чип.",
  ),
  quiz(
    "smartphones",
    "tr-phone-q2",
    "Квіз",
    "Що головне пояснити про середній сегмент?",
    [
      { id: "a", label: "Що там завжди бездротова зарядка" },
      { id: "b", label: "Баланс камери, швидкості й автономності на щодень", correct: true },
      { id: "c", label: "Що це завжди дешевше за бюджет" },
    ],
    "Середній сегмент — про щоденний комфорт без переплати за флагман.",
  ),
  {
    id: "tr-phone-sum",
    sectionId: "smartphones",
    type: "summary",
    title: "Секцію пройдено",
    body: "Ти вмієш вести: сценарій → полиця → 2–3 хіти → допродаж чохла/скла.",
  },

  // LAPTOPS
  {
    id: "tr-lap-intro",
    sectionId: "laptops",
    type: "intro",
    title: "Ноутбуки: як думати",
    body: "Задача перша: універ / офіс / дорога / ігри. Бюджет другий. Модель третя.",
  },
  {
    id: "tr-lap-term-1",
    sectionId: "laptops",
    type: "term",
    title: "Термін",
    body: "Запам’ятай різницю 8 vs 16 ГБ.",
    termId: "t-ram-laptop",
  },
  {
    id: "tr-lap-term-2",
    sectionId: "laptops",
    type: "term",
    title: "Термін",
    body: "Не плутай офісний і ігровий сценарій.",
    termId: "t-igpu",
  },
  {
    id: "tr-lap-band",
    sectionId: "laptops",
    type: "band",
    title: "Три полиці",
    body: "Бюджет — навчання. Середній — робота без гальм. Преміум — ігри/Mac/максимальна мобільність.",
  },
  {
    id: "tr-lap-p1",
    sectionId: "laptops",
    type: "product",
    title: "Хіт",
    body: "Базова відповідь на універ.",
    productId: "laptop-office-budget",
  },
  {
    id: "tr-lap-p2",
    sectionId: "laptops",
    type: "product",
    title: "Хіт",
    body: "Коли вкладок багато.",
    productId: "laptop-student-mid",
  },
  {
    id: "tr-lap-compare",
    sectionId: "laptops",
    type: "compare",
    title: "Порівняй",
    body: "Легкий робочий vs ігровий.",
    compareIds: ["laptop-ultrabook-mid", "laptop-gaming"],
  },
  {
    id: "tr-lap-sc",
    sectionId: "laptops",
    type: "scenario",
    title: "Клиент сказав",
    body: "Відпрацюй відповідь.",
    scenarioId: "sc-laptop-uni",
  },
  quiz(
    "laptops",
    "tr-lap-q1",
    "Квіз",
    "Студент: Zoom + конспекти, бюджет обмежений. Що сказати про ігровий ноут?",
    [
      { id: "a", label: "Брати обов’язково, стане в пригоді" },
      { id: "b", label: "Не потрібен: важчий, гучніший, батарея гірша для пар", correct: true },
      { id: "c", label: "Ігровий завжди дешевший" },
    ],
    "Ігровий — лише під реальну задачу.",
  ),
  {
    id: "tr-lap-sum",
    sectionId: "laptops",
    type: "summary",
    title: "Секцію пройдено",
    body: "Питай задачу → ОЗП/SSD → вага/батарея → допродаж миші й сумки.",
  },

  // TVS
  {
    id: "tr-tv-intro",
    sectionId: "tvs",
    type: "intro",
    title: "ТВ: як думати",
    body: "Кімната й відстань → діагональ → матриця → Smart/звук.",
  },
  {
    id: "tr-tv-term-1",
    sectionId: "tvs",
    type: "term",
    title: "Термін",
    body: "Матриці простими словами.",
    termId: "t-panel-tv",
  },
  {
    id: "tr-tv-term-2",
    sectionId: "tvs",
    type: "term",
    title: "Термін",
    body: "Діагональ без магії.",
    termId: "t-diag",
  },
  {
    id: "tr-tv-band",
    sectionId: "tvs",
    type: "band",
    title: "Три полиці",
    body: "Бюджет — кухня/дача. Середній — вітальня. Преміум — QLED/OLED під сценарій.",
  },
  {
    id: "tr-tv-p1",
    sectionId: "tvs",
    type: "product",
    title: "Хіт",
    body: "Основний сімейний ТВ.",
    productId: "tv-50-mid",
  },
  {
    id: "tr-tv-compare",
    sectionId: "tvs",
    type: "compare",
    title: "Порівняй",
    body: "QLED vs OLED.",
    compareIds: ["tv-55-qled", "tv-55-oled"],
  },
  {
    id: "tr-tv-sc",
    sectionId: "tvs",
    type: "scenario",
    title: "Клиент сказав",
    body: "Кіно ввечері.",
    scenarioId: "sc-tv-movies",
  },
  quiz(
    "tvs",
    "tr-tv-q1",
    "Квіз",
    "Світла вітальня з великими вікнами. Що частіше логічніше?",
    [
      { id: "a", label: "OLED як єдиний правильний варіант" },
      { id: "b", label: "QLED / яскравий преміум LCD", correct: true },
      { id: "c", label: "Найменша діагональ у магазині" },
    ],
    "У світлі важлива яскравість; OLED сяє в темніших умовах.",
  ),
  {
    id: "tr-tv-sum",
    sectionId: "tvs",
    type: "summary",
    title: "Секцію пройдено",
    body: "Не забудь кріплення, HDMI і саундбар як допродаж.",
  },

  // WASHERS
  {
    id: "tr-wash-intro",
    sectionId: "washers",
    type: "intro",
    title: "Пралки: як думати",
    body: "Склад сім’ї → кг → інвертор → програми/пар.",
  },
  {
    id: "tr-wash-term-1",
    sectionId: "washers",
    type: "term",
    title: "Термін",
    body: "Інвертор без води.",
    termId: "t-inverter-wash",
  },
  {
    id: "tr-wash-term-2",
    sectionId: "washers",
    type: "term",
    title: "Термін",
    body: "Кілограми завантаження.",
    termId: "t-load-kg",
  },
  {
    id: "tr-wash-p1",
    sectionId: "washers",
    type: "product",
    title: "Хіт",
    body: "Сімейний стандарт.",
    productId: "washer-7-inv",
  },
  {
    id: "tr-wash-compare",
    sectionId: "washers",
    type: "compare",
    title: "Порівняй",
    body: "Бюджет vs середній.",
    compareIds: ["washer-5-6", "washer-7-inv"],
  },
  {
    id: "tr-wash-sc",
    sectionId: "washers",
    type: "scenario",
    title: "Клиент сказав",
    body: "Сім’я з дитиною.",
    scenarioId: "sc-wash-family",
  },
  quiz(
    "washers",
    "tr-wash-q1",
    "Квіз",
    "Сім’я з 3 осіб регулярно пере постіль. Який орієнтир?",
    [
      { id: "a", label: "5 кг без інвертора «бо дешевше»" },
      { id: "b", label: "7–8 кг з інвертором", correct: true },
      { id: "c", label: "Сушилка замість пралки" },
    ],
    "Об’єм і інвертор закривають біль болю краще за найнижчу ціну.",
  ),
  {
    id: "tr-wash-sum",
    sectionId: "washers",
    type: "summary",
    title: "Секцію пройдено",
    body: "Підключення й гарантія — частина розмови, не післямова.",
  },

  // FRIDGES
  {
    id: "tr-fr-intro",
    sectionId: "fridges",
    type: "intro",
    title: "Холодильники",
    body: "Виміри → об’єм → No Frost → зони/тиша.",
  },
  {
    id: "tr-fr-term-1",
    sectionId: "fridges",
    type: "term",
    title: "Термін",
    body: "No Frost.",
    termId: "t-nofrost",
  },
  {
    id: "tr-fr-p1",
    sectionId: "fridges",
    type: "product",
    title: "Хіт",
    body: "Сімейний середній.",
    productId: "fridge-family-nf",
  },
  {
    id: "tr-fr-compare",
    sectionId: "fridges",
    type: "compare",
    title: "Порівняй",
    body: "Оренда vs сім’я.",
    compareIds: ["fridge-small", "fridge-family-nf"],
  },
  {
    id: "tr-fr-sc",
    sectionId: "fridges",
    type: "scenario",
    title: "Клиент сказав",
    body: "Оренда.",
    scenarioId: "sc-fridge-rent",
  },
  quiz(
    "fridges",
    "tr-fr-q1",
    "Квіз",
    "Що спитати першим на маленькій кухні?",
    [
      { id: "a", label: "Який колір у тренді" },
      { id: "b", label: "Виміри ніші й ширину проходу", correct: true },
      { id: "c", label: "Чи є льодогенератор обов’язково" },
    ],
    "Спочатку фізика простору.",
  ),
  {
    id: "tr-fr-sum",
    sectionId: "fridges",
    type: "summary",
    title: "Секцію пройдено",
    body: "Виміри зберігають і клієнта, і твою нервову систему.",
  },

  // ACS
  {
    id: "tr-ac-intro",
    sectionId: "acs",
    type: "intro",
    title: "Кондиціонери",
    body: "Площа → BTU → інвертор → шум/Wi‑Fi → монтаж.",
  },
  {
    id: "tr-ac-term-1",
    sectionId: "acs",
    type: "term",
    title: "Термін",
    body: "BTU.",
    termId: "t-btu",
  },
  {
    id: "tr-ac-term-2",
    sectionId: "acs",
    type: "term",
    title: "Термін",
    body: "Інвертор.",
    termId: "t-inverter-ac",
  },
  {
    id: "tr-ac-p1",
    sectionId: "acs",
    type: "product",
    title: "Хіт",
    body: "Типовий домашній.",
    productId: "ac-12-inv",
  },
  {
    id: "tr-ac-sc",
    sectionId: "acs",
    type: "scenario",
    title: "Клиент сказав",
    body: "Спальня без реву.",
    scenarioId: "sc-ac-sleep",
  },
  quiz(
    "acs",
    "tr-ac-q1",
    "Квіз",
    "Навіщо інвертор у спальні?",
    [
      { id: "a", label: "Щоб яскравіше світився дисплей" },
      { id: "b", label: "Рівніше тримає температуру й зазвичай тихіший", correct: true },
      { id: "c", label: "Щоб не потрібен був монтаж" },
    ],
    "Комфорт сну = інвертор + правильна потужність.",
  ),
  {
    id: "tr-ac-sum",
    sectionId: "acs",
    type: "summary",
    title: "Секцію пройдено",
    body: "Монтаж — частина продажу, не дрібниця «потім».",
  },

  // MICROWAVES
  {
    id: "tr-mw-intro",
    sectionId: "microwaves",
    type: "intro",
    title: "Мікрохвильовки",
    body: "Гріти / гриль / пекти — три різні продажі.",
  },
  {
    id: "tr-mw-term-1",
    sectionId: "microwaves",
    type: "term",
    title: "Термін",
    body: "Режими.",
    termId: "t-mw-modes",
  },
  {
    id: "tr-mw-compare",
    sectionId: "microwaves",
    type: "compare",
    title: "Порівняй",
    body: "Соло vs гриль.",
    compareIds: ["mw-basic", "mw-grill"],
  },
  {
    id: "tr-mw-sc",
    sectionId: "microwaves",
    type: "scenario",
    title: "Клиент сказав",
    body: "Тільки гріти.",
    scenarioId: "sc-mw-heat",
  },
  quiz(
    "microwaves",
    "tr-mw-q1",
    "Квіз",
    "Клієнт тільки гріє суп. Що логічно?",
    [
      { id: "a", label: "Конвекція преміум обов’язково" },
      { id: "b", label: "Бюджетна соло 20 л", correct: true },
      { id: "c", label: "Вбудована духовка замість НВЧ завжди" },
    ],
    "Не продавай функції без сценарію.",
  ),
  {
    id: "tr-mw-sum",
    sectionId: "microwaves",
    type: "summary",
    title: "Секцію пройдено",
    body: "Об’єм під сім’ю + чесний режим під задачу.",
  },

  // VACUUMS
  {
    id: "tr-vac-intro",
    sectionId: "vacuums",
    type: "intro",
    title: "Пилососи",
    body: "Тип підлоги + тварини + «швидко щодня» чи «глибоко раз на тиждень».",
  },
  {
    id: "tr-vac-term-1",
    sectionId: "vacuums",
    type: "term",
    title: "Термін",
    body: "Три типи.",
    termId: "t-vac-types",
  },
  {
    id: "tr-vac-compare",
    sectionId: "vacuums",
    type: "compare",
    title: "Порівняй",
    body: "Вертикаль vs робот.",
    compareIds: ["vac-stick", "vac-robot"],
  },
  {
    id: "tr-vac-sc",
    sectionId: "vacuums",
    type: "scenario",
    title: "Клиент сказав",
    body: "Кіт линяє.",
    scenarioId: "sc-vac-cat",
  },
  quiz(
    "vacuums",
    "tr-vac-q1",
    "Квіз",
    "Робот замінює класику повністю?",
    [
      { id: "a", label: "Так, завжди" },
      { id: "b", label: "Ні, частіше це підтримка чистоти", correct: true },
      { id: "c", label: "Тільки якщо немає килимів будь-яких" },
    ],
    "Чесність будує довіру й повторні покупки.",
  ),
  {
    id: "tr-vac-sum",
    sectionId: "vacuums",
    type: "summary",
    title: "Секцію пройдено",
    body: "Підбереш тип — половина продажу вже зроблена.",
  },

  // HAIR DRYERS
  {
    id: "tr-dry-intro",
    sectionId: "hair-dryers",
    type: "intro",
    title: "Фени",
    body: "Потужність → іони → насадки → як часто укладають.",
  },
  {
    id: "tr-dry-term-1",
    sectionId: "hair-dryers",
    type: "term",
    title: "Термін",
    body: "Іонізація.",
    termId: "t-ions",
  },
  {
    id: "tr-dry-p1",
    sectionId: "hair-dryers",
    type: "product",
    title: "Хіт",
    body: "Середній з іонами.",
    productId: "dryer-ions",
  },
  {
    id: "tr-dry-sc",
    sectionId: "hair-dryers",
    type: "scenario",
    title: "Клиент сказав",
    body: "Подарунок, менше пушіння.",
    scenarioId: "sc-dryer-gift",
  },
  quiz(
    "hair-dryers",
    "tr-dry-q1",
    "Квіз",
    "Що сказати про іонізацію просто?",
    [
      { id: "a", label: "Це тільки маркетинг без сенсу" },
      { id: "b", label: "Менше електризується, виглядає гладше", correct: true },
      { id: "c", label: "Фен стає бездротовим" },
    ],
    "Проста мова продає краще за техжаргон.",
  ),
  {
    id: "tr-dry-sum",
    sectionId: "hair-dryers",
    type: "summary",
    title: "Секцію пройдено",
    body: "Уточни довжину волосся й чи потрібен дифузор.",
  },

  // STYLERS
  {
    id: "tr-st-intro",
    sectionId: "stylers",
    type: "intro",
    title: "Стайлери",
    body: "Одна задача (вирівняти) vs багато укладок (мультистайлер).",
  },
  {
    id: "tr-st-term-1",
    sectionId: "stylers",
    type: "term",
    title: "Термін",
    body: "Температура.",
    termId: "t-temp-plates",
  },
  {
    id: "tr-st-compare",
    sectionId: "stylers",
    type: "compare",
    title: "Порівняй",
    body: "Випрямляч vs мультистайлер.",
    compareIds: ["straightener-mid", "styler-multi"],
  },
  {
    id: "tr-st-sc",
    sectionId: "stylers",
    type: "scenario",
    title: "Клиент сказав",
    body: "І рівно, і локони.",
    scenarioId: "sc-styler",
  },
  quiz(
    "stylers",
    "tr-st-q1",
    "Квіз",
    "Клієнт вирівнює чубчик раз на місяць. Що логічно?",
    [
      { id: "a", label: "Найдорожчий мультистайлер обов’язково" },
      { id: "b", label: "Бюджетний/середній випрямляч", correct: true },
      { id: "c", label: "Тільки професійний фен без стайлера" },
    ],
    "Частота використання визначає полицю.",
  ),
  {
    id: "tr-st-sum",
    sectionId: "stylers",
    type: "summary",
    title: "Секцію пройдено",
    body: "Не продавай набір насадок тому, хто хоче одну кнопку «вирівняти».",
  },
];
